### ISSUE TITLE
[Bug]: matchPath doesn't work with optional parameters

### ISSUE THREAD

**Issue by hugofelp** [remix-run/react-router#9933] opened 2023-01-18 17:21 UTC
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

// match:
console.log(matchPath('/segment1/:segment2', '/segment1/mandatoryParam'));

// doesn't match:
console.log(matchPath('/segment1/:segment2?', '/segment1/optionalParam'));
console.log(matchPath('/segment1/:segment2?', '/segment1/'));
console.log(matchPath('/segment1/:segment2?', '/segment1'));

### Expected Behavior

Expected patterns with optional parameter to be matched.

### Actual Behavior

Patterns with optional parameter return `null`

**Comment by brophdawg11** [comment] 2023-01-23 22:21
Duplicate of https://github.com/remix-run/react-router/issues/9793 / https://github.com/remix-run/react-router/discussions/9862

**Closed by brophdawg11** 2023-01-23 22:21 UTC
Labels: bug
