### ISSUE TITLE
[Bug]: Nested routes under an id with a trailing - (dash) fail to match bug

### ISSUE THREAD

**Issue by ThatOneAwkwardGuy** [remix-run/react-router#8359] opened 2021-11-18 19:58 UTC
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

```
<Routes>
   <Route path="/dashboard/:dashboardId" element={<DashboardPage />}>
      <Route path="edit" element={<EditDasbhboard />}>
   </Route>
</Routes>
```

### Expected Behavior

for the route to match :dashbaordId even with the trailing slash 

e.g 
```
/dashboard/T0UXC0u4indapMWh3ySE-/cases
```

### Actual Behavior

shows my 404 page because it can't find any matches

**Comment by timdorr** [comment] 2021-11-18 21:19
Duplicate of #8288

**Closed by timdorr** 2021-11-18 21:19 UTC
Labels: bug
