### ISSUE TITLE
[v6] history.block() replacement?

### ISSUE THREAD

**Issue by yanickrochon** [remix-run/react-router#8216] opened 2021-11-04 14:30 UTC
The migration guide from v5 to v6 does not mention how to replace `history.block`. We are using this in a custom hook to prevent page navigation when a form is dirty. What is the migration from this function now that `useHistory` has been replaced?

**Comment by timdorr** [comment] 2021-11-04 15:17
Duplicate of #8139

**Closed by timdorr** 2021-11-04 15:17 UTC
