### ISSUE TITLE
[Bug]: v6.0.0-beta.4: `Routes` renders any garbage as long as `path` and `element` props are provided to it

### ISSUE THREAD

**Issue by wojtekmaj** [remix-run/react-router#8063] opened 2021-09-22 14:23 UTC
### What version of React Router are you using?

v6.0.0-beta.4

### Steps to Reproduce

`Routes` seems to be rendering any garbage as long as `path` and `element` props are provided to it.

1. Real-life example (discussed in #8033):
https://codesandbox.io/s/react-router-render-issue-2nssk?file=/src/App.js

2. Invalid code example
https://codesandbox.io/s/react-router-render-issue-2-2ew9s?file=/src/App.js:688-698

#### Expected Behavior

* AuthRoute to be called correctly
* AuthRoute to redirect users away from guarded page to Login page

#### Actual Behavior

* `AuthRoute` is not being called
* `element` passed to `AuthRoute` is being rendered without any authentication

#### Expected Behavior

* App to crash as we're trying to render `42` as React component.

#### Actual Behavior

* App isn't crashing
* `element` passed to `NotEvenAProperComponent` is being rendered

### Comment

I think the fact #8033 has already multiple duplicates should give a hint on why this issue needs more love.

* There is no mention in release notes about this change: a VERY popular pattern suddenly stopped working without any explanation.
* Example 2 proves `Routes` behavior in 6.0.0-beta.4 is ridiculous and creates hard to debug errors. 

* If you really have a good reason for `Routes` to only accept `Route`s (although personally I doubt that the benefits would ever outweigh the costs), then do just that: *filter out* all children which aren't `Route`s, and/or throw when this happens.

**Comment by las3r** [comment] 2021-09-22 14:53
I can second this. Upgrading from beta.2 to beta.4 destroyed my app completely. I'm using a similar approach rendering stuff like:

```ts
<PrivateRoute path='share/:id' element={<WizardShare />}></PrivateRoute>
```

This completely blows up the app, and doesn't render the `<WizardShare />` as my `console.log` are not hit inside the component. Not sure what went wrong, but this has worked all the way from v4. It's a big change if you really want it.

**Comment by timdorr** [comment] 2021-09-22 17:42
The ability to render non-Route components under Switch/Routes was never an announced feature. In fact, [the docs specifically said not to do this](https://github.com/remix-run/react-router/blame/51925ded7530516cfb8d9756fa0190e3b4f49387/packages/react-router/docs/api/Switch.md#L84). We can't announce the removal of something that was never official supported or documented.

There are plenty of ways to do the exact same thing. Most involve moving up your auth checks inline with your routes. For instance, this is some code directly from one of my real apps in v5:
```js
<Switch>
  // ...
  {(!currentTeam || currentTeam.role == 'owner') && <Route path="/teams/:team/billing" component={Billing} />}
```

You can also isolate any authenticated routes into their own component and run an auth check before rendering them at all. 

```js
<Switch>
  <Route path="/login" component={Login} />
  <Route path="/logout" component={Logout} />
  <Route path="/signup" component={Signup} />
  <Route path="/" component={AuthRoutes} />
</Switch>

const AuthRoutes = () => {
 return !isLoggedIn ? <Redirect to="/login"> : <Switch> //...
}
```

That's the rough idea. These concepts work for both v5 and v6. 

Duplicate of #8033

**Closed by timdorr** 2021-09-22 17:42 UTC

**Comment by wojtekmaj** [comment] 2021-09-22 20:42
@timdorr I understand your rationale, but I still think that:
* Given the popularity of this non-documented feature it deserves a mention that it is patched and no longer possible. It would also greatly improve DX to throw a warning on runtime should such situation occur.
* Example 2 which is what this ticket is mainly about is NOT a duplicate. Routes components behaves in a very unpredictable, bug-prone way, especially when taken into consideration pt 1 was not addressed.
