### ISSUE TITLE
[Bug]: React-router docs page examples showing empty pages.

### ISSUE THREAD

**Issue by JESii** [remix-run/react-router#7973] opened 2021-08-24 14:05 UTC
### What version of React Router are you using?

This is the documentation page at https://reactrouter.com/web/guides/quick-start

### Steps to Reproduce

- Visit the docs page https://reactrouter.com/
- Click 'web'
- Click on any of the "Examples" pages
- E.g., 'Basic"

### Expected Behavior

should see the examples

### Actual Behavior

Get an empty page -- 
![2021-08-24 at 6 58 AM](https://user-images.githubusercontent.com/486/130630795-317736aa-83a4-4bf4-85eb-d140ce34e0ca.png)

**Comment by pshrmn** [comment] 2021-08-24 15:05
Duplicate of https://github.com/remix-run/react-router/issues/7951 (or possibly you have privacy badger running and that is blocking codesandbox)

**Closed** 2021-08-24 15:06 UTC

**Comment by JESii** [comment] 2021-08-25 12:39
Nope — no privacy badger and I get to code sandbox everywhere else… thanks
