### ISSUE TITLE
using vite plugin react({ jsxImportSource: '@emotion/react' }), failed

### ISSUE THREAD

**Issue by JerrySLau** [remix-run/react-router#12664] opened 2024-12-31 03:18 UTC
### I'm using React Router as a...

framework

### Reproduction

https://github.com/JerrySLau/issues-react-router-example.git

commit id 699cc9722dc40aedb6f3d08905c8a1f11c912cbd

### System Info

```shell
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M3
    Memory: 80.48 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.5 - ~/.nvm/versions/node/v18.20.5/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.5/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v18.20.5/bin/npm
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 18.2
  npmPackages:
    @react-router/dev: ^7.1.1 => 7.1.1 
    @react-router/express: ^7.1.1 => 7.1.1 
    @react-router/fs-routes: ^7.1.1 => 7.1.1 
    @react-router/node: ^7.1.1 => 7.1.1 
    react-router: ^7.1.1 => 7.1.1 
    vite: ^5.4.0 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

render test page correctly

### Actual Behavior

after I add vite plugin like:
```
import { reactRouter } from "@react-router/dev/vite";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import react from '@vitejs/plugin-react-swc';

export default defineConfig({
  plugins: [
    react({ jsxImportSource: '@emotion/react' }),
    reactRouter(),
    tsconfigPaths()
  ],
});
```

Uncaught SyntaxError: Identifier 'prevRefreshReg' has already been declared (at root.tsx:29:7)

```
// [BEGIN] REACT REFRESH BODY --------------------------------------------------
import { withComponentProps as _withComponentProps } from "/@id/__x00__virtual:react-router/with-props";
if (!window.$RefreshReg$) throw new Error("React refresh preamble was not loaded. Something is wrong.");
const prevRefreshReg = window.$RefreshReg$;
const prevRefreshSig = window.$RefreshSig$;
window.$RefreshReg$ = RefreshRuntime.getRefreshReg("/Users/Jerry/projects/fe-test/express-example/src/root.tsx");
window.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;
```

**Comment by timdorr** [comment] 2024-12-31 18:06
Duplicate of #12352

**Closed by timdorr** 2024-12-31 18:06 UTC
Labels: bug
