### ISSUE TITLE
[Docs]: Warning logs contains link leading to a 404

### ISSUE THREAD

**Issue by BenoitZugmeyer** [remix-run/react-router#12386] opened 2024-11-25 11:17 UTC
### Describe what's incorrect/missing in the documentation

With v6.28.0, we started to have warnings like:
* ⚠️ React Router Future Flag Warning: React Router will begin wrapping state updates in `React.startTransition` in v7. You can use the `v7_startTransition` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_starttransition.
* ⚠️ React Router Future Flag Warning: Relative route resolution within Splat routes is changing in v7. You can use the `v7_relativeSplatPath` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_relativesplatpath.

Those links are leading to a 404 page. On my machine, https://reactrouter.com/v6/upgrading/future redirects to https://reactrouter.com/en/6.28.0/upgrading/future which is non-existant.

**Comment by timdorr** [comment] 2024-11-29 18:13
Duplicate of #12383

**Closed by timdorr** 2024-11-29 18:13 UTC
Labels: docs
