### ISSUE TITLE
Markdown files generate invalid route types

### ISSUE THREAD

**Issue by mattoni** [remix-run/react-router#12561] opened 2024-12-16 17:47 UTC
### I'm using React Router as a...

framework

### Reproduction

Tried making a repro on StackBlitz, but react router requires node v20 and stackblitz is locked to v18.

Essentially, when using .md files (with the proper plugins in vite), the generated route types have type errors in them that make typescript fail

- Add MD files and plugin to vite
- expand generated types folder and notice they have a type error on the import line.

### System Info

```shell
System:
    OS: Linux 6.12 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 14.19 GB / 46.95 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 23.4.0 - /usr/local/share/nvm/versions/node/v23.4.0/bin/node
    npm: 10.9.2 - /usr/local/share/nvm/versions/node/v23.4.0/bin/npm
    pnpm: 9.12.3 - /usr/local/share/nvm/versions/node/v23.4.0/bin/pnpm
```

### Used Package Manager

pnpm

### Expected Behavior

Generated types don't have type errors

### Actual Behavior

![image](https://github.com/user-attachments/assets/3e9f0a35-8875-495d-b507-635fb1754196)

I'm assuming this is happening because it's looking for a ts/js file in the matched route, when in reality its a .md file.

**Comment by timdorr** [comment] 2024-12-16 20:41
Duplicate of #12362

**Closed by timdorr** 2024-12-16 20:41 UTC
Labels: bug
