### ISSUE TITLE
[Bug]: the below code working , i think this is bug

### ISSUE THREAD

**Issue by AmanjDev** [remix-run/react-router#8090] opened 2021-10-01 06:36 UTC
### What version of React Router are you using?

v6

### Steps to Reproduce

```js
interface Props {
    element: React.ReactElement;
    requiredRoles: Array<Roles>;
    path?: string;
}

const MyRoute = ({element, requiredRoles, ...rest}:Props)=>{
    return (
        <div>dsfs</div>
    )
}

const MainRouter = ()=>{
    return (
        <>
            <Router>
                <Routes>
                    <Route path="/login" element={<Login/>}/>
                    <Route path="/" element={<Loading message="login to dashboard ..."/>}/>
                    <MyRoute path="/dashboard" element={<Main/>} requiredRoles={[Roles.ADMIN]}/>
                </Routes>
            </Router>
        </>
    )
}
```

### Expected Behavior

showing error

### Actual Behavior

showing Main component content

**Comment by timdorr** [comment] 2021-10-04 01:21
Duplicate of #8033

**Closed by timdorr** 2021-10-04 01:21 UTC
