### ISSUE TITLE
[Bug]: `loader` not respecting ancestor suspense

### ISSUE THREAD

**Issue by filipjakov** [remix-run/react-router#10838] opened 2023-09-04 12:52 UTC
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

Have more/less the following jsx structure:

```tsx
<Suspense key="suspense-fallback" fallback={AppLoader}>
  <EnvironmentContext>
    <AppRoutes />
  </EnvironmentContext>
</Suspense>;

```

where `EnvironmentContext` suspends while fetching data and then attaches that data to the `window.config`.

`AppRoutes` uses `createBrowserRouter` to create the app routes. The main meat is:

```tsx
{
  path: "accounts",
  element: ...,
  children: [
    { index: true, Component: ... },
    {
      path: ":userId",
      loader: async () => {
        if (!window.config["KEY"]) {
          return redirect("/not-found");
        }

        return null;
      },
      Component: ...,
    },
  ],
},
```

### Expected Behavior

`loader` triggers before the `window.config` is set and errors (`undefined` window.config); looks like the router code does not get suspended. Expected behavior?

Also, using:

```
"react": "^17.0.1",
"react-query": "3.16",
"react-router-dom": "6.15.0",
```

### Actual Behavior

`loader` triggers after `window.config` is set as it does not get rendered until `EnvironmentContext` is not finished suspending.

**Comment by brophdawg11** [comment] 2023-09-05 15:12
Can you provide a minimal reproduction?  It's hard to say what's going on exactly without one.

Loaders will run as soon as you call `createBrowserRouter` since data fetching and rendering are decoupled by design in `RouterProvider`.  Generally you don't want to be creating your router inside the render-tree as that can get into very odd behavior/issues with StrictMode and component unmounts, creations of duplicate routers and history listeners, etc.  Instead, your router should be a singleton created outside of the React tree.

I think what I would do is create a Promise for the config values and leverage that in your loaders instead of directly accessing a value which introduces race conditions such as this one.

> Also, seems like await + redirect combination is not working?

You cannot redirect from a `defer` Promise because the "Response" has already been sent from the loader.  The data resolved into the promise is sent as-is to the client, there's no additional processing if you resolve with a `Response`.  You would need to send back the URL you want to redirect to as data and manually redirect with `useNavigate` inside the `Await` component.

**Comment by filipjakov** [comment] 2023-09-06 07:40
> Generally you don't want to be creating your router inside the render-tree as that can get into very odd behavior/issues with StrictMode and component unmounts, creations of duplicate routers and history listeners, etc. Instead, your router should be a singleton created outside of the React tree.

I think this was the main problem, thank you for the explanations.

All of this was a way to try and remove some routes from the router based on some configuration fetched from the API. Is there a way to do it with the `RouterProvider`?

**Comment by brophdawg11** [comment] 2023-09-06 15:40
The real key is just create the router once and never touch it again, so instead of creating it and trying to remov e routes, just hold off on creating it until you know what the final set of routes is.

The canonical way is probably with [`useSyncExternalStore`](https://react.dev/reference/react/useSyncExternalStore) but you can also just use a module scoped variable - and be sure you only initialize it the first time.  I think something like this would work:

```jsx
let router;

function App() {
  let { routes } = useFetchRoutes(); // This should suspend while fetching routes
  
  if (!router) {
    router = createBrowserRouter(routes);
  }

  return <RouterProvider router={router} fallbackElement={<AppLoader />} />;
}
```

**Closed by brophdawg11** 2023-09-06 15:40 UTC
Labels: bug
