### ISSUE TITLE
[Bug]: HashRouter: browser's back button and `navigate(-1)` not work in some cases

### ISSUE THREAD

**Issue by reminjp** [remix-run/react-router#9966] opened 2023-01-24 06:27 UTC
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

1. Open https://codesandbox.io/s/react-router-6-7-0-hash-router-back-p0bztk
   - It uses `HashRouter` of react-router-dom@6.7.0.
2. Click the "Sub Page" link.
3. Press the "Back" button.

### Expected Behavior

Navigates to the root page.

### Actual Behavior

Doesn't navigate.
It isn't reproduced when using react-router-dom@6.6.2.

**Comment by timdorr** [comment] 2023-01-24 16:12
Looks like #9709 is causing this, but I have no specific idea why. @chaance or @brophdawg11 might have a better idea than me.

**Comment by brophdawg11** [comment] 2023-01-24 16:36
I think this might be a codesandbox quirk.  If I copy that `HashRouter` example down  into `examples/basic` in the repository and install 6.7.0 there it works as expected for me

**Comment by reminjp** [comment] 2023-01-24 22:48
Thank you for replying. You're right! I noticed my codesandbox example doesn't reproduce the issue in local.

However, it was reproduced on my full app. Other components or dependencies might break `HashRouter`. I'll keep investigating the causes.

**Comment by chaance** [comment] 2023-01-24 23:04
Closing for now, but let us know if you can isolate the issue outside of the codesandbox and get us a repro to look at 👍

**Comment by brophdawg11** [comment] 2023-01-25 19:40
Thanks for the reproduction @shartte!

**Comment by brophdawg11** [comment] 2023-01-26 18:33
This should be fixed now in `6.8.0` 👍

**Closed by brophdawg11** 2023-01-26 18:33 UTC
Labels: bug
