### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by c0d3x** [remix-run/react-router#8468] opened 2021-12-10 11:00 UTC
### What version of React Router are you using?

6

### Steps to Reproduce

```TS
import { createHashHistory } from 'history';

const customHistory = createHashHistory();

customHistory.push('/my-route')
```

### Expected Behavior

The route should be re-rendered.

### Actual Behavior

When using a hashRouter and triggering a new location change after a back-end request returns within an action.ts file.
The route will change in the URL, but the component is not rendered.

If there is a new way of doing this, please update the manual how you can trigger the navigation not having to rely on react hooks.

This problem is mainly for external actions files and class components.

**Comment by timdorr** [comment] 2021-12-10 14:33
Duplicate of #8264

**Closed by timdorr** 2021-12-10 14:33 UTC
Labels: bug
