### ISSUE TITLE
[Bug]: ScrollRestoration incompatible with createBrowserRouter(..., { window })

### ISSUE THREAD

**Issue by CGamesPlay** [remix-run/react-router#9656] opened 2022-11-30 09:57 UTC
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

The [ScrollRestoration component](https://github.com/remix-run/react-router/blob/37f2d36948ed1e0751751acf62cab391b22c0c9c/packages/react-router-dom/index.tsx#L1030) relies explicitly on the ambient `window` and `document` objects, but a router can be [configured with a custom window](https://reactrouter.com/en/main/routers/create-browser-router#window), which means that the ambient one is unsuitable.

Mount an `<iframe src>` where the src has the same Origin as the global window, then mount a `<ScrollRestoration />` inside of this iframe (you can mount the entire app inside the iframe; it doesn't matter).

### Expected Behavior

When the iframe navigates, the scroll within the iframe is restored.

### Actual Behavior

The parent window has it's scroll saved/restored by the ScrollRestoration, despite the component being mounted in a different window.

Note that this code changed recently with #9573 however the new implementation still relies on the ambient `document`, so even specifying an ID inside of the iframe would not resolve the issue.

**Comment by brophdawg11** [comment] 2023-01-23 23:12
Duplicate of https://github.com/remix-run/react-router/discussions/9495 - please go upvote that proposal if you'd like to see this considered!

**Closed by brophdawg11** 2023-01-23 23:12 UTC
Labels: bug
