### ISSUE TITLE
Create `v6.0.0.0-beta.0` to `v6` migration guide

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#8196] opened 2021-11-03 23:25 UTC
We actually sat around on beta.0 for a long time and I know there are thousands, if not hundreds of thousands of apps using it.

Anybody want to go review the release notes here on GitHub for each beta release to create a quick set of steps to upgrade from `beta.0` to the final `v6` API?

Put the file in `docs/upgrading.md`

🙏

**Comment by mjackson** [comment] 2021-11-05 05:26
I really don't think this is necessary. The betas did contain some breaking changes, but for the most part it was just stuff that was either intended behavior that we just didn't get right or stuff that people really wanted from v5 that we didn't have in v6 yet.

**Comment by wojtekmaj** [comment] 2021-11-05 09:25
6.0.0-beta.0 gets ~4% of weekly downloads of 5.2.0 (and 5.2.0 only, not entire 5.x branch). 

Going through all the betas myself I didn't find anything particularly unclear when reading through release notes. Things were _challenging_ (some of my apps are stuck on beta.6 because of relative routing or `useBlocker` usage), but never _unclear_.

Plus, beta is a beta and kinda comes with "use at own risk" label.

**Comment by PolancichBen** [comment] 2021-11-09 00:23
Not sure if it helps with the idea, but I'd personally love it. Im currently dealing with a bug that I inherited using `v6.0.0.0-beta.0` where the basename for `BrowserRouter` is throwing an error of 
```js
TypeError
Cannot read properties of null (reading 'replace')
in normalizePathname
```

I upgraded to v6.0.0 and v6.0.1 and the error still remains after clearing modules and rerunning builds. Any thoughts as to why this could occur?

**Comment by chaserda** [comment] 2021-11-15 19:58
^ per above im also running into an issue applying index to a route and getting the following after going from beta to release

```Type 'true' is not assignable to type 'false | undefined'```

**Comment by davedx** [comment] 2021-11-23 12:51
I'm also stuck because our application returns functions that return `<Route/>` in multiple places, but that doesn't work anymore because <Route/> has to be directly inside <Router> and cannot be wrapped. I honestly don't know how to fix it.

**Comment by timdorr** [comment] 2022-01-16 02:26
I'm going to close this out because I've seen very few issues related to upgrading from the betas, compared to the number coming from v5.

**Closed by timdorr** 2022-01-16 02:26 UTC
