### ISSUE TITLE
[Bug]: Cannot test a component with useNavigate and useBlocker

### ISSUE THREAD

**Issue by djonathas** [remix-run/react-router#11189] opened 2024-01-12 20:34 UTC
### What version of React Router are you using?

6.21.0

### Steps to Reproduce

Create a test from a component within useNavigate() and useBlock()
```
const navigate = useNavigate()
const blocker = useBlocker(() => true)
```

### Expected Behavior

be able to run the test successfully

### Actual Behavior

I receive two types of error. First, I receive an error like that:
`useNavigate() may be used only in the context of a <Router> component.`

If I put a `<Router>` like `<MemoryRouter>,` I can solve this error but I receive other:
`useBlocker must be used within a data router.  See https://reactrouter.com/routers/picking-a-router.`

And if I change to use a data router like using createMemoryRouter, the error from useNavigate comes back. So in the end, I can't test the both hooks at same time in the component.

I believe the solution is the useBlocker needs to accept the `<MemoryRouter>` like the useNavigate.

**Comment by timdorr** [comment] 2024-01-13 00:59
Duplicate of #11155

**Closed by timdorr** 2024-01-13 00:59 UTC
Labels: bug

**Comment by djonathas** [comment] 2024-01-23 11:51
I think this bug I posted is different from the #11155, I don't receive the same error message and my case it is specific during the unit tests

**Comment by ThaynarLima** [comment] 2024-05-28 16:49
I had same problem and by looking at the test from the repo and later found this issue
![image](https://github.com/remix-run/react-router/assets/167218119/421b300d-81a4-44cf-964f-28bd2a9841e3)

i did the same and just rendered the RouterProvider wrapped on my other stuff

![image](https://github.com/remix-run/react-router/assets/167218119/8ae4c6bd-e71a-4bec-b37f-aee36758e787)
