### ISSUE TITLE
[Bug]: No possibility to disable error boundary detection for data routers

### ISSUE THREAD

**Issue by aerialist7** [remix-run/react-router#10257] opened 2023-03-24 07:45 UTC
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

I used `BrowserRouter` and I have no possibility to disable error boundary detection for data router.

So I decided to create a custom router for use instead of `BrowserRouter` which will have a `detectErrorBoundary` function that always returns `false` to ignore error handling. 
But it has no effect. 

Is it a bug? 

Sample: https://codesandbox.io/s/react-router-v6-custom-router-disabled-error-boundary-0xwks2?file=/src/App.jsx

### Expected Behavior

There is the possibility to disable error boundary detection for custom router

### Actual Behavior

There is NO possibility to disable error boundary detection for custom router

**Comment by brophdawg11** [comment] 2023-03-24 20:33
This is by design - we want to encourage applications to consider error handling, but in the worst case RR will always catch errors and give you _something_.  Can you explain your use case for not wanting error handling?  Is it just that you want the `React.lazy` to to throw to an outer `<Suspense>` Boundary?

I might suggest looking at [`route.lazy`](https://reactrouter.com/en/main/route/lazy) (explained more in this [blog post](https://remix.run/blog/lazy-loading-routes)) for lazy loading not just your components, but also your loaders - and doing so without a render/fetch waterfall.

**Comment by aerialist7** [comment] 2023-03-28 06:29
>> Can you explain your use case for not wanting error handling?

We also have a custom error handler and it doesn't work after migration to data routers

**Comment by aerialist7** [comment] 2023-03-29 07:59
Thank you for the answer, but it is not what we need.
Setting custom `RouteObject.ErrorBoundary` gives me the ability to customize the visualization of error, but I need to customize error-handling logic. 
In other words, I need to create my own [react `ErrorBoundary`](https://legacy.reactjs.org/docs/error-boundaries.html) component and replace react-router `ErrorBoundary` with my own. How can I do it?

**Comment by timdorr** [comment] 2023-03-29 16:06
More specifically, there needs to be a way to disable [`RenderErrorBoundary`](https://github.com/remix-run/react-router/blob/d3ab8c39a69655867879ef34831def26dc72bf3a/packages/react-router/lib/hooks.tsx#L669-L675) when desired.

**Comment by brophdawg11** [comment] 2023-03-29 17:56
> How can I do it?

You can't 😄 

I'm going to close this out since it's working as intended, and it turns out there is already a [proposal](https://github.com/remix-run/react-router/discussions/10166) for this so please go give that an upvote to get it moving through our [Open Development Process](https://remix.run/blog/open-development).  Thanks!

**Closed by brophdawg11** 2023-03-29 17:56 UTC
Labels: bug
