### ISSUE TITLE
[Bug]: useRevalidate function not revalidating if url hash present 

### ISSUE THREAD

**Issue by ts213** [remix-run/react-router#10512] opened 2023-05-20 16:49 UTC
### What version of React Router are you using?

6.11.2

### Steps to Reproduce

https://codesandbox.io/s/bold-darkness-jnkngv
Click revalidate button multiple times.
Click link.
Click revalidate button multiple times again.

### Expected Behavior

Loader for the current URL should be called regardless of the URL hash.

### Actual Behavior

 Loader doesn't get called if a url contains a hash.

**Comment by akamfoad** [comment] 2023-05-22 08:12
I can confirm, you cannot revalidate when there is a hash in the link, this happens because react-router will short-circuit and return early if the navigation goes to the same hash (same link with same hash should not trigger reload in Web, or re-validation in RR) but manual re-validation trigger should not take hashes into account. I think this is what causes this behavior

https://github.com/akamfoad/react-router/blob/edf6dca2c6dde5e86f2e3e3ae8b62996d87f4ab3/packages/router/router.ts#L1228-L1240

**Comment by brophdawg11** [comment] 2023-05-23 14:33
This is fixed by #10516 and will be available once the next release goes out - likely `6.12.0`

**Closed by brophdawg11** 2023-05-23 14:33 UTC
Labels: bug
