### ISSUE TITLE
[Feature]: Cleanup for BrowserRouter

### ISSUE THREAD

**Issue by mrzie** [remix-run/react-router#8578] opened 2022-01-14 03:35 UTC
### What is the new or updated feature that you are suggesting?

everytime BrowserRouter mounted would create a new history instance by `createBrowserHistory`, it calls `addEventListener` but didn't remove event listeners in unmount phase.
How about use a global history instance or export cleanup method in `history` package?

### Why should this feature be included?

if BrowserRouter mount/unmount for many times in an app, many listeners would be redundant.
Also doing side effects in render phase is unsafe for concurrent mode.

**Comment by brophdawg11** [comment] 2023-01-09 21:12
I don't think this is an issue since the return value of `history.listen` is a cleanup function, and that's returned from `useLayoutEffect` so it should be cleaned up on unmount.  I'm going to close this out but if you can provide a reproduction in code sandbox please re-open!

**Closed by brophdawg11** 2023-01-09 21:12 UTC
Labels: feature
