### ISSUE TITLE
[Bug]: In an SSR application, navigate immediately, and react-router does not execute data loader

### ISSUE THREAD

**Issue by yimingjfe** [remix-run/react-router#11093] opened 2023-12-06 12:34 UTC
### What version of React Router are you using?

6.17.0

### Steps to Reproduce

1. In an SSR application, ensure that there are two routing components that have their own data loader and use the data from the data loader.
2. Visit  route "a", then visit route "b", refresh the page, and back to route "a"  immediately.
3. You will get an error ”Cannot read properties of undefined“, because the data loader is not executed, the data in the data loader cannot be accessed.

You can reproduce by example https://github.com/remix-run/examples/tree/main/routes-gen of Remix

1. First, visit the "products" route.
2. Visit the route "products/1" by clicking "Cool products".
3. Refresh the page，return by clicking back button of browser immediately.
4. You can find the function "startNavigation" isn't invoked, so the data loader not be executed.

### Expected Behavior

When navigating, the startNavigation function should be invoked, data loaders should be executed, I found that the problem may be related to the [initialized variable assignment](https://github.com/remix-run/react-router/blob/426b055ad7d569f12cc2f19d48875081477a67fe/packages/router/router.ts#L807) .

### Actual Behavior

In the SSR application, the data loader of the react-router is not executed during quick navigation.

**Comment by brophdawg11** [comment] 2023-12-14 16:23
This is an edge case scenario that the SSR setup would need to handle on it's own.  I believe the basic issue you're running into is as follows:

* Assume you start on `/a` and click through to `/b` and do a hard reload
* The server receives a request for `/b`, calls loaders, and renders HTML for `/b` which includes hydration data
* The browser receives the `/b` HTML and starts loading JS files for `/b`
* While JS files are loading, you hit the back button to `/a`
* JS files finish loading and they initialize/hydrate `RouterProvider` which hydrates to the current `window.location` of `/a`
* This causes a hydration errors because we're hydrating the SSR HTML for `/b` with the client-side VDOM for `/a` and there is no hydration data for `/a`

Remix handles this by checking the Server Rendered URL against the URL at the time of hydration and performing a hard reload of the new location if it detects a mismatch (since it's knows that hydration will fail): https://github.com/remix-run/remix/blob/main/packages/remix-react/browser.tsx#L201

We thought this was a solved issue but we have had very rare reports of occasional flows where the mismatch isn't detected properly and the reload doesn't trigger, so we have kept this issue open in Remix: https://github.com/remix-run/remix/issues/7080.  Since they are very rare, there is no consistent reproduction flow, and a browser reload by the user fixes the issue it hasn't been high on the priority list.

I tried reproducing against https://github.com/remix-run/examples/tree/main/routes-gen using the steps above and in all cases that I was able to trigger the mismatch, Remix detected it and performed the hard reload of `/products` accordingly (there are temporarily hydration error sin the browser and a flash of an error boundary in the UI before the reload completes).  the key to reproducing the mismatch that I've found is you need to throttle your network connection and when you reload, click the back button _After_ the HTML doc has completed loading but _before_ the subsequent JS scripts have completed loading.

I'm going to close this as a dup of https://github.com/remix-run/remix/issues/7080 since it's not really a React Router issue specifically, but an SSR framework issue.  If you have any additional info or ways to reliably reproduce, please add them over there!

**Closed by brophdawg11** 2023-12-14 16:23 UTC
Labels: bug

**Comment by yimingjfe** [comment] 2023-12-18 18:29
> This is an edge case scenario that the SSR setup would need to handle on it's own. I believe the basic issue you're running into is as follows:
> 
> * Assume you start on `/a` and click through to `/b` and do a hard reload
> * The server receives a request for `/b`, calls loaders, and renders HTML for `/b` which includes hydration data
> * The browser receives the `/b` HTML and starts loading JS files for `/b`
> * While JS files are loading, you hit the back button to `/a`
> * JS files finish loading and they initialize/hydrate `RouterProvider` which hydrates to the current `window.location` of `/a`
> * This causes a hydration errors because we're hydrating the SSR HTML for `/b` with the client-side VDOM for `/a` and there is no hydration data for `/a`
> 
> Remix handles this by checking the Server Rendered URL against the URL at the time of hydration and performing a hard reload of the new location if it detects a mismatch (since it's knows that hydration will fail): https://github.com/remix-run/remix/blob/main/packages/remix-react/browser.tsx#L201
> 
> We thought this was a solved issue but we have had very rare reports of occasional flows where the mismatch isn't detected properly and the reload doesn't trigger, so we have kept this issue open in Remix: [remix-run/remix#7080](https://github.com/remix-run/remix/issues/7080). Since they are very rare, there is no consistent reproduction flow, and a browser reload by the user fixes the issue it hasn't been high on the priority list.
> 
> I tried reproducing against https://github.com/remix-run/examples/tree/main/routes-gen using the steps above and in all cases that I was able to trigger the mismatch, Remix detected it and performed the hard reload of `/products` accordingly (there are temporarily hydration error sin the browser and a flash of an error boundary in the UI before the reload completes). the key to reproducing the mismatch that I've found is you need to throttle your network connection and when you reload, click the back button _After_ the HTML doc has completed loading but _before_ the subsequent JS scripts have completed loading.
> 
> I'm going to close this as a dup of [remix-run/remix#7080](https://github.com/remix-run/remix/issues/7080) since it's not really a React Router issue specifically, but an SSR framework issue. If you have any additional info or ways to reliably reproduce, please add them over there!

Thank you very much for your detailed reply. Indeed, as you said, it will cause a hydration error and should be handled by SSR itself for this boundary case.
