### ISSUE TITLE
[Feature]: useSearchParams hook takes a function as initial parameter

### ISSUE THREAD

**Issue by vldmr1986** [remix-run/react-router#9198] opened 2022-08-30 18:30 UTC
### What is the new or updated feature that you are suggesting?

I can't use function as a parameter of useSearchParams hook.

```
const [searchParams, setSearchParams] = useSearchParams(() => {
        const initialSearchParams = new URLSearchParams(window.location.search); // browser API
        // do some validation of params
        if (!["asc","desc"].includes(initialSearchParams.get("sortorder")) initialSearchParams.set("sortorder", "asc");
        // other validation
        return initialSearchParams;
})
```

### Why should this feature be included?

For example user types: ?sortorder=invalid
So, if the user passes invalid parameters in the URL, my component will render with invalid parameters.

I can place some logic inside the useEffect:
```
const [searchParams, setSearchParams] = useSearchParams();
useEffect(()={
        if (!["asc","desc"].includes(initialSearchParams.get("sortorder"))  {
           searchParams.set("sortorder", "asc");
           setSearchParams(searchParams, {replace: true})
// but in this case I will send 2 requests to the server, the first one with the invalid parameter
}
},[])
```

**Comment by timdorr** [comment] 2022-08-30 20:53
What you're requesting happen is essentially a duplicate of #8908

**Closed by timdorr** 2022-08-30 20:53 UTC
Labels: feature
