### ISSUE TITLE
[Bug]: navigate doesn't work with nested routes

### ISSUE THREAD

**Issue by manavana-pierroldin** [remix-run/react-router#8844] opened 2022-05-04 13:33 UTC
### What version of React Router are you using?

V6

### Steps to Reproduce

you have some nested routes:

```
<Routes>
      <Route path="/personnel/:id" >
            <Route path="" element={<AuthGuard ROLE="ACQUISITION"><Principale /> </AuthGuard>}>
              <Route path="acquisition" element={<GestionAcquisition />}>
                <Route 
                  path="" 
                  element={<TableauDeBordAcquisition/>}
                  />
                <Route 
                  path="appelsoffres" 
                  element={<AppelsOffres />}
                  />
                <Route
                  path="appelsoffres/:idAppel"
                  element={<DetailAppelOffre />}
                  /> 
                <Route
                  path="creationappelsoffres"
                  element={<CreationAppelOffre />}
                  />
                <Route path="offres" element={<Offres/>} />
                <Route
                  path="offres/:idOffre"
                  element={<DetailsOffre/>}
                />
                <Route
                  path="creationoffres"
                  element={<CreationOffre/>}
                />
                <Route path="marche" element={<Marche />} />

                <Route path="fournisseurs" element={<Fournisseurs />} />
              </Route>
            </Route>
          </Route>
</Routes>
```

you try to use navigate to jump to one of these locations:
`navigate("/personnel/1/acquisition/appelsoffres")`

### Expected Behavior

should redirect to the mentioned location, but no, (this works perfectly with non nested routes)

### Actual Behavior

you get the follwing error:

> TypeError: Cannot read properties of undefined (reading 'pathname')
>   at resolveTo (router.ts:549:1)
>  at hooks.tsx:252:1
>    at mountMemo (react-dom.development.js:15846:1)
>    at Object.useMemo (react-dom.development.js:16219:1)
>    at useMemo (react.development.js:1532:1)
>    at useResolvedPath (hooks.tsx:252:1)
>    at useHref (hooks.tsx:40:1)
>    at LinkWithRef (index.tsx:267:1)
>    at renderWithHooks (react-dom.development.js:14985:1)
>    at updateForwardRef (react-dom.development.js:17044:1)``

**Comment by timdorr** [comment] 2022-05-04 16:56
Duplicate of #8489

**Closed by timdorr** 2022-05-04 16:56 UTC
Labels: bug
