### ISSUE TITLE
[Bug]: react-router-dom@6.28 feature warnings break tests with `vitest-fail-on-console` enabled

### ISSUE THREAD

**Issue by artaommahe** [remix-run/react-router#12259] opened 2024-11-11 10:06 UTC
### What version of React Router are you using?

6.28

### Steps to Reproduce

- have a test with router usage for a component that triggers any feature warning
- have `vitest-fail-on-console` (or similar) enabled
- see the test failing

### Expected Behavior

there is should be an easy way to disable those warnings for tests without manually updating all `<MemoryRouter ...` usages with the whole features list

### Actual Behavior

you have to manually list all those features for each failing test

**Comment by timdorr** [comment] 2024-11-11 15:42
Duplicate of #12250

**Comment by timdorr** [comment] 2024-11-11 15:43
Sorry, I know it's not an _exact_ duplicate of that issue, but I'd like to keep the warnings issues limited to one so we can track when they are removed.

**Closed by timdorr** 2024-11-11 15:42 UTC
Labels: bug
