### ISSUE TITLE
Broken Links in Animated Transitions

### ISSUE THREAD

**Issue by Balestra78** [remix-run/react-router#8157] opened 2021-10-20 15:50 UTC
Hi,

i found a broken link here: 
https://reactrouter.com/web/example/animated-transitions

I need examples ;)

## Version

**5.3.0.**

## Test Case

https://reactrouter.com/web/example/animated-transitions

**Comment by timdorr** [comment] 2021-10-20 17:46
Duplicate of #8149

**Closed by timdorr** 2021-10-20 17:46 UTC
