### ISSUE TITLE
[Bug]: accidental import from a wrong router module causes a crash and inadequate error

### ISSUE THREAD

**Issue by jayarjo** [remix-run/react-router#8761] opened 2022-04-03 07:46 UTC
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

Wrap an `App` component with `BrowserRouter` from `react-router-dom` and in one of child components import `useNavigate` from `react-router`. 

### Expected Behavior

Error should specify a proper reason for the failure. In this case I was using `useNavigate` inside the Router context. Only when I opened the source and read the following comment I got additional info for further troubleshooting:

![image](https://user-images.githubusercontent.com/150075/161417033-b27ea1a2-d674-4a02-81c1-f89227332b91.png)

And still it was kind of misleading, 'cause my initial interpretation was that I was importing and double wrapping an App in two routers somehow. The App that I was porting to react-router is huge and I spent whole weekend, looking for a problem. Which in reality happened to be that fact that I was importing BrowserRouter from react-router-dom and useNavigate from react-router.

I didn't even had a mental picture of potential reasons, 'cause importing from react-router was a result of auto-completion. So I wasn't even aware that I have it.

### Actual Behavior

Described steps will result in the following error:

```
Uncaught Error: useNavigate() may be used only in the context of a <Router> component.
```

Which doesn't have anything to do with the problem.

**Comment by timdorr** [comment] 2022-04-04 02:48
Duplicate of #8721

**Closed by timdorr** 2022-04-04 02:48 UTC
Labels: bug
