### ISSUE TITLE
[Bug]: Returning Route from component not working.

### ISSUE THREAD

**Issue by danyhiol** [remix-run/react-router#8054] opened 2021-09-19 00:00 UTC
### What version of React Router are you using?

6.0.0-beta.4

### Steps to Reproduce

https://codesandbox.io/s/youthful-minsky-2q8rp?file=/src/App.js:455-459

### Expected Behavior

1. Create a react component return a `Route`:

`const Test = () => <Route path="test" element={<h2>TEST</h2>} />;`

2. Render component inside `Routes`

```
<Routes>
      ...
      <Test />
</Routes>
```
3. Go to /test.
Test should be rendered on route chancge.

### Actual Behavior

Test is not rendered. 

Just occurred since the last update.

**Comment by timdorr** [comment] 2021-09-19 01:41
Duplicate of #8050

**Closed by timdorr** 2021-09-19 01:41 UTC
