### ISSUE TITLE
[Bug]: Match route does not work if there is a minus sign at the beginning

### ISSUE THREAD

**Issue by kulakowka** [remix-run/react-router#8525] opened 2021-12-22 16:39 UTC
### What version of React Router are you using?

6.2.1

### Steps to Reproduce

```js
<Routes>
      <Route path="/users/:id" element={<UserApp />} />
</Routes>
```

### Expected Behavior

`/users/-wYVsb1KDtT9YJJFUiSTq0dqUyvc5vK51nx7QW29CPJc` - This route is matched

### Actual Behavior

`/users/-wYVsb1KDtT9YJJFUiSTq0dqUyvc5vK51nx7QW29CPJc` - This route is NOT matched

`/users/wYVsb1KDtT9YJJFUiSTq0dqUyvc5vK51nx7QW29CPJc` - This route is matched

I think the problem is in the mechanism that is looking for a suitable route. 

Anything that starts with a symbol `-` is not matched.

**Comment by ivansvlv** [comment] 2021-12-22 16:54
I've just noted the same bug but if you have a "." in the route. 

e.g. this wouldn't match to the path - `login/reset/:resetToken`:

`login/reset/Djdfsd32afasdg.kdaf324asdf.adsgGsd`

however this path - `login/reset/:resetToke/success` will be matched:

`login/reset/Djdfsd32afasdg.kdaf324asdf.adsgGsd/success`

**Comment by ivansvlv** [comment] 2021-12-22 17:22
I'm entirely new to the codebase of `react-router`, but I was able to track it down to the place where I believe this can happen - https://github.com/remix-run/react-router/blob/main/packages/react-router/index.tsx#L1208

`\w+` would match only these characters - `[a-zA-Z0-9_]`

**Comment by kulakowka** [comment] 2022-01-02 10:50
@mjackson Sorry to bother you. This bug is critical for us. We have already uploaded the new version of our application to production. Please pay attention to this problem. Probably there is an error somewhere in the regular expressions. Surely this can be fixed very quickly.

**Comment by benkraus** [comment] 2022-01-03 21:32
https://github.com/remix-run/remix/issues/819 relates here. We had to hack that patch in (probably breaking something else wrt routing) in order to get `.well-known` paths to match correctly.

**Comment by edbella** [comment] 2022-01-12 14:40
Update: This also breaks when there is a `-` at the end as well, not just at the beginning

**Comment by seeden** [comment] 2022-01-20 19:18
Same problem for @ character at the beginning

**Comment by zwily** [comment] 2022-01-20 23:01
In Remix, I can't use a splat path on any path with a hyphen anywhere in it. So, `app/routes/cdn-cgi.image.$.js` does NOT work for matching `/cdn-cgi/image/foo`, but `app/routes/cdncgi.image.$.js` DOES match `/cdncgi/image/foo`. Sounds like it's possibly related.

**Comment by joacub** [comment] 2022-02-04 18:47
same here, this was working before, what happened ?

thanks in advance

**Comment by joacub** [comment] 2022-02-07 21:09
Is there any advance on this, I can’t update my application becouse of this.

**Comment by egerrek** [comment] 2022-02-11 17:28
I have problem with cyrillic symbols. The route beginning with the Cyrillic character is not found.

Steps to Reproduce
<Routes>
      <Route path="/users/:id" element={<UserApp />} />
</Routes>
Expected Behavior
/users/михаил - This route is matched

Actual Behavior
/users/михаил - This route is NOT matched

/users/michael - This route is matched

**Comment by dartandrevinsky** [comment] 2022-02-11 19:47
> I have problem with cyrillic symbols. The route beginning with the Cyrillic character is not found.
> 
> Steps to Reproduce <Route path="/users/:id" element={} /> Expected Behavior /users/михаил - This route is matched
> 
> Actual Behavior /users/михаил - This route is NOT matched
> 
> /users/michael - This route is matched

Try and analyze the regexes in play yourself - maybe you will be able to spot the error, file a PR, or - fork the repo and use it as a dependency directly:

https://github.com/remix-run/react-router/blob/a7a77da997eaa2eb447a7e30915e1f92e401c118/packages/react-router/index.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L1188-L1231

**Comment by knpwrs** [comment] 2022-02-20 03:05
This bug is what causes this: https://github.com/remix-run/remix/issues/2012

**Comment by troyschneringer** [comment] 2022-02-25 01:57
@dartandrevinsky and @egerrek 

I think the issue can be traced to https://github.com/remix-run/react-router/blob/main/packages/react-router/index.tsx#L1225

The problem with using `\b` in the regex is that its only matching the equivalent of `[a-zA-Z0-9_]`.  

I'm not a regex expert and am not finding an equivalent of `\b` to use that handles unicode characters.

**Comment by brophdawg11** [comment] 2022-02-28 16:30
Fixed in #8563

**Closed by brophdawg11** 2022-02-28 16:30 UTC
Labels: bug

**Comment by troyschneringer** [comment] 2022-02-28 16:43
@brophdawg11 the fix is #8563 doesn't appear to address the issue with routes that start with `@` not matching.  Is this intentional?

**Comment by knpwrs** [comment] 2022-02-28 16:47
@troyschneringer it appears that of `@`, `.`, `-`, and `~`, only `@` gets urlencoded by `encodeURIComponent`:

```sh
$ echo "@.-~" | tr -d '\n' | node -e 'process.stdout.write(encodeURIComponent(require("fs").readFileSync(0, "utf-8")))'
%40.-~
```

The fix does support url-encoded characters, though I'm not sure how browsers handle `@` when they are sent in the URL.

**Comment by brophdawg11** [comment] 2022-02-28 16:50
@troyschneringer Yeah that's intentional per the `Unreserved Characters` section of [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) referenced in the PR.  Preceding that is the section on `Reserved Characters` which includes `@` and indicates that URLs should be encoding `@` ahead of time:

> 2.2.  Reserved Characters
>
>   URIs include components and subcomponents that are delimited by
>   characters in the "reserved" set.  These characters are called
>   "reserved" because they may (or may not) be defined as delimiters by
>   the generic syntax, by each scheme-specific syntax, or by the
>   implementation-specific syntax of a URI's dereferencing algorithm.
>   If data for a URI component would conflict with a reserved
>   character's purpose as a delimiter, then the conflicting data must be
>   percent-encoded before the URI is formed.
>
>      reserved    = gen-delims / sub-delims
>
>      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
>
>      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
>                  / "*" / "+" / "," / ";" / "="

**Comment by TrevorSayre** [comment] 2022-02-28 21:16
@brophdawg11 So are routes like https://www.npmjs.com/package/@types/node in violation of RFC 3986 and thus react-router won't support it, despite this existing in the wild?

**Comment by brophdawg11** [comment] 2022-02-28 23:40
I wouldn't consider it a hard "won't support it" based on #8563 alone - `@` in particular hasn't been given a lot of thought since it was not the original issue in this bug or #8561.  The RFC section I mentioned above spoke more to why the PR author chose to support `~`/`-`/`.` as they are explicitly `Unreserved Characters`.

I would vote that support for Reserved Characters such as `@` be discussed separately in a new discussion/issue so they can be properly evaluated.

**Comment by nvdxdy** [comment] 2022-03-05 13:23
The matchRoutes function does not match routes if there is cyrillic symbol at the beginning.

Version 6.2.2 fixed this behavior for HashRouter (routes like #/ы for example, did not work in version 6.2.1), but the matchRoutes function still does not work if there is cyrillic symbol at the beginning.

What version of React Router are you using?
6.2.2

Steps to Reproduce:
const routes = [
	{
		element: <AppContainer />,
		children: [
			{
				path: "/:lang",
				element: <Search />
			}
		]
	}
];
const matchedRoutes = matchRoutes(routes, "/ы", "/base");

Expected Behavior:
/base/ы - Matched

Actual Behavior:
/base/s - Matched
/base/ы - Not matched

**Comment by kiliman** [comment] 2022-03-17 17:11
> 2.2. Reserved Characters
> 
> URIs include components and subcomponents that are delimited by
characters in the "reserved" set. These characters are called
"reserved" because they may (or may not) be defined as delimiters by
the generic syntax, by each scheme-specific syntax, or by the
implementation-specific syntax of a URI's dereferencing algorithm.

I think the operative phrase here is *"... they may (or may not) be defined as delimiters by
the generic syntax, by each scheme-specific syntax..."*

I believe standard URLs (via `http:` and `https:` schemes) treat `@` as a regular character. Same with `mailto:` (otherwise you'd have to encode the `@` in email addresses.

**Comment by knpwrs** [comment] 2022-03-31 21:37
It would be great to support `@` in paths. I made a remix site that was intended to support `@` in URLs but it doesn't work.

- This works: https://npm.im/@remix-run/server-runtime
- This works: https://git.pizza/remix-run
- This does not work: https://git.pizza/@remix-run/server-runtime (or any other scoped package)
