### ISSUE TITLE
[Bug]: NavLink, presumably, does not evaluate `isActive` correctly for pathnames with placeholders

### ISSUE THREAD

**Issue by birdofpreyru** [remix-run/react-router#8277] opened 2021-11-08 17:35 UTC
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

I believe, I spotted a mistake comparing your source code with my implementation of a similar functionality. This code:
https://github.com/remix-run/react-router/blob/11714bfa4e206305b65fc3d3523216467ba3a769/packages/react-router-dom/index.tsx#L269-L283

Say `to` contains a placeholder: `path/with/:param`, and `<NavLink>` is rendered at the route `path/with/value`. Currently, the `pathname` in location object from `useLocation()` will be the actual path `path/with/value`, while the resolved path from `useResolvedPath()` will be the original template pathname `path/with/:param`. So, at the line 280 you'll compare `locationPathname === toPathname` is false, while I believe it is expected to compare to true (not sure what the other part of condition `!end && ...` does, but it probably covers some other edge-case).

My current implementation of similar functionality (a hook testing whether the current path is a given `to`) is:
```js
const { pathname } = useResolvedPath(to);
const isActive = !!useMatch(pathname);
```
and I believe that is what you need inside `<NavLink>` (or something more optimal, looking for which was my reason to look at that source code).

### Expected Behavior

See above.

### Actual Behavior

See above.

**Comment by brophdawg11** [comment] 2023-01-24 17:34
The implementation has changed a good bit since 6.0.1 and in my quick test this is not an issue (`NavLink` is working correctly for parameterized routes) so I'm going to close this out.  Please feel free to re-open with a reproduction if this is still an issue!

**Closed by brophdawg11** 2023-01-24 17:34 UTC
Labels: bug
