### ISSUE TITLE
[Bug]: (v7) react-router packages and pnpm compatibility  

### ISSUE THREAD

**Issue by lucaquerella** [remix-run/react-router#12266] opened 2024-11-12 15:57 UTC
### What version of React Router are you using?

v7

### Steps to Reproduce

- https://reactrouter.com/dev/framework/start/installation follow this guide
- use typescript and pnpm (instead of npm)

### Expected Behavior

no typing error

### Actual Behavior

I get typing error:
-` Cannot find module 'react-router' or its corresponding type declarations.ts(2307)
`
-`Cannot find module '@react-router/dev/routes' or its corresponding type declarations.ts(2307)
`

when I import:
```
import { Outlet, Scripts, ScrollRestoration } from "react-router";
import { index } from "@react-router/dev/routes";

```
if I add:
  ```
  "baseUrl": ".",
    "paths": {
      "@react-router/dev/routes": ["./node_modules/@react-router/dev/dist/routes.d.ts"],
      "react-router": ["./node_modules/react-router/dist/index.d.ts"],
    }
```

everything works fine.

here my full `tsconfig.json`
```
{

  "compilerOptions": {
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "target": "ES2022",
    "module": "ES2022",
    "skipLibCheck": false,
    "strict": true,
    "jsx": "react",
    "moduleResolution": "Bundler",
    "baseUrl": ".",
    "paths": {
      "@react-router/dev/routes": ["./node_modules/@react-router/dev/dist/routes.d.ts"],
      "react-router": ["./node_modules/react-router/dist/index.d.ts"],
    }
  }
}
 
```

**Comment by stephen776** [comment] 2024-11-22 15:12
Same issue here

**Comment by pcattori** [comment] 2024-11-25 20:47
Closing as I couldn't reproduce this locally on MacOS with pnpm v9.12.3 and React Router v7.0.1 .

If you can provide a reproduction, I'm happy to reopen this issue.

**Closed by pcattori** 2024-11-25 20:47 UTC
Labels: bug
