### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by spykelion** [remix-run/react-router#8713] opened 2022-03-10 17:39 UTC
### What is the new or updated feature that you are suggesting?

Search within the api docs

### Why should this feature be included?

I find it difficult navigating the v6 docs. A search will be great

**Comment by timdorr** [comment] 2022-03-11 03:44
Ironically, this is a duplicate issue you could have searched for ;)

Duplicate of #8501

**Closed by timdorr** 2022-03-11 03:44 UTC
Labels: feature
