### ISSUE TITLE
[Bug]: (v7) Prerendering Fails with React 19

### ISSUE THREAD

**Issue by abdel-17** [remix-run/react-router#12138] opened 2024-10-17 04:27 UTC
### What version of React Router are you using?

7.0.0-pre.1

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-cibu2u?file=app%2Fhome.jsx
2. Run `pnpm build`

### Expected Behavior

It should build successfully.

### Actual Behavior

It fails with a cryptic error likely due to React's internals changing.

**Comment by mayank99** [comment] 2024-12-06 15:27
This can still be reproduced with the latest stable versions of React and React Router. Updated repro link: https://stackblitz.com/edit/vitejs-vite-wlza4m?file=package.json&terminal=build

<details><summary>Logs</summary>

```console
❯ npm run build

> react-router build

vite v6.0.3 building for production...
✓ 41 modules transformed.
build/client/.vite/manifest.json                  1.11 kB │ gzip:  0.32 kB
build/client/assets/home-DMjzBprG.js              0.18 kB │ gzip:  0.17 kB
build/client/assets/with-props-BxDUxdVQ.js        0.44 kB │ gzip:  0.22 kB
build/client/assets/root-Dj_cnf6b.js              0.52 kB │ gzip:  0.32 kB
build/client/assets/chunk-D52XG6IA-CIXPXIh-.js  103.03 kB │ gzip: 34.93 kB
build/client/assets/entry.client-BOCz0HeL.js    179.29 kB │ gzip: 56.87 kB
✓ built in 1.38s
vite v6.0.3 building SSR bundle for production...
✓ 8 modules transformed.
build/server/.vite/manifest.json  0.17 kB
build/server/index.js             5.43 kB
[getOwner@/node_modules/react/cjs/react.development.js#cjs:416:54
exports.createElement@/node_modules/react/cjs/react.development.js#cjs:1330:61
getRouteComponents@/node_modules/react-router/dist/development/index.js#cjs:6209:104
createServerRoutes/<@/node_modules/react-router/dist/development/index.js#cjs:6229:10
createServerRoutes@/node_modules/react-router/dist/development/index.js#cjs:6222:45
ServerRouter@/node_modules/react-router/dist/development/index.js#cjs:8215:34
…
[getOwner@/node_modules/react/cjs/react.development.js#cjs:416:54
exports.createElement@/node_modules/react/cjs/react.development.js#cjs:1330:61
getRouteComponents@/node_modules/react-router/dist/development/index.js#cjs:6209:104
createServerRoutes/<@/node_modules/react-router/dist/development/index.js#cjs:6229:10
createServerRoutes@/node_modules/react-router/dist/development/index.js#cjs:6222:45
ServerRouter@/node_modules/react-router/dist/development/index.js#cjs:8215:34
…

x Build failed in 276ms
[react-router] Prerender: Received a 500 status code from `entry.server.tsx` while prerendering the `/` path.
Unexpected Server Error
    at validatePrerenderedResponse (/node_modules/@react-router/dev/dist/vite.js:2635:11)
    at prerenderRoute (/node_modules/@react-router/dev/dist/vite.js:2599:30) {
  code: 'PLUGIN_ERROR',
  plugin: 'react-router',
  hook: 'writeBundle'
}
```

</details>

**Comment by Fredkiss3** [comment] 2024-12-09 01:58
I have found a simple way to fix this issue is to run `NODE_ENV=production` before building the app like this :

```
NODE_ENV=production npm run build
``` 

It seems like this issue is discussed here : https://github.com/remix-run/react-router/issues/12078

**Comment by brookslybrand** [comment] 2024-12-09 19:24
@Fredkiss3 is correct, this is the way to force the proper NODE_ENV for React to build correctly

To be determined if we change how the defaults are setup, so I'll leave this issue open. However, for anyone looking at this issue, this is a proper solution (also true if you have `ssr: false` set or are using `react-router-serve`)

**Comment by connorjs** [comment] 2024-12-14 14:33
This also affects `ssr: false` for SPA builds. I wonder why we even build/generate the server code when we have `ssr: false` (but that would be a separate issue).

_Just mentioning since this issue and linked PR helped me understand and fix._

**Comment by brophdawg11** [comment] 2024-12-18 19:47
`ssr: false` disables _runtime_ server rendering.  We still need to perform server rendering at _build time_ to generate your `index.html` file

**Comment by brophdawg11** [comment] 2024-12-18 19:48
This should be fixed by https://github.com/remix-run/react-router/pull/12578 and available in the next release

**Closed by brophdawg11** 2024-12-18 19:48 UTC
Labels: bug, awaiting release, v7

**Comment by connorjs** [comment] 2024-12-21 00:41
> `ssr: false` disables _runtime_ server rendering. We still need to perform server rendering at _build time_ to generate your `index.html` file

@brophdawg11 - I really appreciated this emphasis. I had not shifted my thinking to this given I was still in "client react router" headspace.

Can we add something to <https://reactrouter.com/how-to/spa> along those lines? I could open an issue/PR if desired.

---

Separately, awesome to hear about `7.1.0`! I will update right away!
