### ISSUE TITLE
[Bug]: MatchPath not working with optional parameter

### ISSUE THREAD

**Issue by grzegorzCieslik95** [remix-run/react-router#10226] opened 2023-03-17 19:58 UTC
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

I have a route with path = `/login/:serviceName?`
When the user goes to pathname -> `matchPath(/login/test )` returns null.

### Expected Behavior

It should work like in v5 

### Actual Behavior

Return null should return true or some object with details

**Comment by timdorr** [comment] 2023-03-18 01:05
Duplicate of https://github.com/remix-run/react-router/issues/9793 / https://github.com/remix-run/react-router/discussions/9862

**Closed by timdorr** 2023-03-18 01:05 UTC
Labels: bug
