### ISSUE TITLE
No search feature makes it incredibly hard to read docs. Please add a search bar! [Feature]: 

### ISSUE THREAD

**Issue by waleedrana777** [remix-run/react-router#8690] opened 2022-02-26 10:16 UTC
### What is the new or updated feature that you are suggesting?

A search bar in documentation site would be nice.

### Why should this feature be included?

To help navigate the documentation of the library

**Comment by timdorr** [comment] 2022-02-27 02:48
Duplicate of #8501

**Closed by timdorr** 2022-02-27 02:48 UTC
Labels: feature
