### ISSUE TITLE
[Bug]: Pathless route broke action [tutorial broken]

### ISSUE THREAD

**Issue by webartoli** [remix-run/react-router#9523] opened 2022-10-30 10:14 UTC
### What version of React Router are you using?

6.4.2

### ⚠️ **This issue affect the main tutorial** ⚠️
User that gave React Router a shot are effected by this.

Following [main tutorial](https://reactrouter.com/en/main/start/tutorial) all works well until [Pathless Route](https://reactrouter.com/en/main/start/tutorial#pathless-routes).

Adding a pathless route as described, the `New` button no longer works.

### Steps

- Create a `root path` with an action
- Add pathless children
- trigger root action

### Expected Behavior

parent action `rootAction` is detected via pathless routes.

In the tutorial, pressing new button the action is detected.

### Actual Behavior

I got a console.warn message:

```
You're trying to submit to a route that does not have an action.  To fix this, please add an `action` function to the route for [/]
```

And an error response
```
ErrorResponse {
  status: 405, 
  statusText: 'Method Not Allowed', 
  data: 'No action found for [/]'
}
```

**Comment by timdorr** [comment] 2022-10-30 17:52
Duplicate of #9284

This will be fixed in 6.4.3.

**Closed by timdorr** 2022-10-30 17:52 UTC
Labels: bug
