### ISSUE TITLE
[Bug]: the loader function not being called in nested routes

### ISSUE THREAD

**Issue by poc7667** [remix-run/react-router#9377] opened 2022-09-29 23:23 UTC
### What version of React Router are you using?

6.4.1

### Steps to Reproduce

Index.tsx
```
                <RouterProvider router={createBrowserRouter(
                    createRoutesFromElements(
                        <Route path={"/*"}
                               loader={()=>{console.log(`App.tsx loader`)}}
                               element={
                            <App />
                        }
                        />
                    ),
                )}/>

```

App.tsx
```

                <Routes>
                    <Route
                        loader={()=>{console.log(`CategoryView.tsx loader`)}}
                        path=':categoryId/*'
                        element={<CategoryView/>}
                    />
                    <Route
                        ...
                    />
                </Routes>
```

### Expected Behavior

When accessing this route **:categoryId/***
Both loaders should be called.

* console.log(`App.tsx loader`)
* console.log(`CategoryView.tsx loader`)

### Actual Behavior

Only  the root level loader is being called ** console.log(`App.tsx loader`)**

**Comment by brophdawg11** [comment] 2022-09-30 01:28
This is a duplicate of #9362 - descendant Routes do not participate in data loading.  We will make this more explicit in the docs.

**Closed by brophdawg11** 2022-09-30 01:28 UTC
Labels: bug
