### ISSUE TITLE
[Bug]: v7_partialHydration:fasle is not allow

### ISSUE THREAD

**Issue by vaynevayne** [remix-run/react-router#12320] opened 2024-11-20 05:39 UTC
### What version of React Router are you using?

6.27

### Steps to Reproduce

many warning 
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/164f693c-0fd6-40e0-8f48-0fa429373411">

set this 
```jsx
  {
    future: {
      v7_partialHydration:true,
    },
  },

```

new waring appeared
<img width="1495" alt="image" src="https://github.com/user-attachments/assets/7bfc3d23-c07a-48d5-bbf4-e0a8f3971969">

### Expected Behavior

when i set   v7_partialHydration:false, 
no wraning  shown

### Actual Behavior

Endless error message warnings
   `v7_partialHydration: false`, 
   Doesn't stop the warning, you assume that server rendering is used all over the world?

**Comment by timdorr** [comment] 2024-11-20 09:19
Duplicate of #12250

**Closed** 2024-11-20 09:19 UTC
Labels: bug
