### ISSUE TITLE
react router 7 with vite-pwa throws error

### ISSUE THREAD

**Issue by agdolla** [remix-run/react-router#12659] opened 2024-12-30 09:02 UTC
### I'm using React Router as a...

framework

### Reproduction

Create a new vite project with react router 7 and vite-pwa plugin
Use `react-router build`

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 71.38 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.5.0 - /opt/homebrew/bin/node
    npm: 11.0.0 - /opt/homebrew/bin/npm
    pnpm: 9.15.1 - /opt/homebrew/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 17.5
  npmPackages:
    @react-router/dev: ^7.1.1 => 7.1.1 
    @react-router/node: ^7.1.1 => 7.1.1 
    react-router: ^7.1.1 => 7.1.1 
    vite: ^6.0.6 => 6.0.6
```

### Used Package Manager

pnpm

### Expected Behavior

my app (react 19, vite, vite-pwa) should work without throwing an error, it works with react router 6.x.x

### Actual Behavior

the app throws an error:
<img width="1257" alt="Screenshot 2024-12-30 at 09 44 38" src="https://github.com/user-attachments/assets/31a297ae-ec40-4252-8309-6456aeabc1e1" />

when I build the app with `vite build` there is no index.html so the app can not work (my app is client only, `ssr: false`)
<img width="1006" alt="Screenshot 2024-12-30 at 09 46 57" src="https://github.com/user-attachments/assets/dce3ac2a-2f7f-465f-862e-1ba2ca949c75" />

So I figured that I need to use `react-router build` although I did not see it in the documentation:
<img width="992" alt="Screenshot 2024-12-30 at 09 50 37" src="https://github.com/user-attachments/assets/c02a26af-2fe7-42b1-b581-0e49f4ab790f" />

As you can see the index.html is generated after the pwa plugin has finished, so the plugin can not put index.html into precache.

**Comment by timdorr** [comment] 2024-12-30 19:00
Duplicate of #12352

**Comment by timdorr** [comment] 2024-12-30 19:01
While this looks separate, this is related to the linked issue because the proposed fix would also allow you to use these kinds of plugins alongside RR's.

**Closed by timdorr** 2024-12-30 19:01 UTC
Labels: bug

**Comment by agdolla** [comment] 2024-12-30 19:40
Sorry, I don't understand what the proposed fix is. In the other issue they call the babel plugin manually but the PWA plugin is already called manually.

**Comment by agdolla** [comment] 2025-04-15 12:49
We went back to 6.x.x

**Comment by KienTPhan** [comment] 2025-05-16 03:16
I have the same issue, what I did to make it work is to run the build twice, not ideal but I can't seem to find another solution. The first build is to generate the index.html and prerender files, the second is for vite-pwa-plugin to precache index.html and all the prerendered files generated from the first build. This seems to do the job but I would love to hear any better solution.

```package.json
"build": "react-router build && react-router build --mode postBuild",
```

```vite.config.ts
export default defineConfig(({ mode, command }) => {
  const isPostBuild = mode === "postbuild";

  return {
    plugins: [
      reactRouter(),
      VitePWA(manifestForPlugIn),
      ...
    ],
    ...
    build: {
      emptyOutDir: isPostBuild ? false : true,  // <--- so we don't lose index.html and prerendered files on the second build
     ...
    }
  };
});

```
