### ISSUE TITLE
[Bug]: Nested navigation triggers rerender in parent component which use useNavigate()

### ISSUE THREAD

**Issue by Mikilll94** [remix-run/react-router#8904] opened 2022-05-25 20:42 UTC
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

1. Open this CodeSandbox: https://codesandbox.io/s/pedantic-frog-80y5jl?file=/src/App.js
2. Open console
3. Change the url to "https://80y5jl.csb.app" and hit ENTER.
4. In the console you will see:

![image](https://user-images.githubusercontent.com/17653648/170363076-196d0db2-5df8-4cc3-9925-37aef694fb6c.png)

As you can see, nested navigation triggered unwanted rerender in parent component which uses `useNavigate()`.

### Expected Behavior

Nested navigation should NOT cause a rerender in parent component which uses `useNavigate()`.

### Actual Behavior

Nested navigation cause a rerender in parent component which uses `useNavigate()`. This is annoying, because i.e. I would make an HTTP request in parent component then it will be fired twice.

**Comment by timdorr** [comment] 2022-05-26 03:38
Duplicate of #7634

**Closed by timdorr** 2022-05-26 03:38 UTC
Labels: bug
