### ISSUE TITLE
[Bug]: Mutation causes a loop that delays action resolvement and potentially an infinite loop

### ISSUE THREAD

**Issue by nemonemi** [remix-run/react-router#11064] opened 2023-11-28 09:13 UTC
### What version of React Router are you using?

6.16.0

### Steps to Reproduce

In an application that on a route has both loaders and actions, when a mutation occurs, and the form is submitted, the loader gets called again, and the screen enters a loop.

This is not an infinite loop, it does finish, but after lots of component lifecycles (shown by the console log and the delayed action)

Note:
The React.Strict is not being applied!

I have also noticed, that if I would call the `useSubmit` manually, after like 5 seconds, the screen component would re-render 6 15 times. This is without any change to the data.
The same thing happens if I call the `useRevalidator`, but this time it got triggered 18 times.

When I reload the screen manually, the console.log is printed out only 3 times.
### Expected Behavior

This type of action should trigger the minimum number of component/screen lifecycles as possible.

### Actual Behavior

The screen doesn't get frozen, but the action takes quite a while to finish, so for example, a modal dialog where an item is selected, and then added to the content of the screen takes several seconds to resolve its action and close (and I'm talking locally).

**Comment by brophdawg11** [comment] 2023-11-28 14:47
Please provide a reproduction so we can look into the setup

**Comment by miclle** [comment] 2023-12-08 08:26
A higher probability occurs in lazy loading mode
https://github.com/remix-run/react-router/blob/dev/examples/lazy-loading/src/App.tsx

**Comment by brophdawg11** [comment] 2023-12-08 17:46
Can you provide a reproduction @nemonemi?

**Comment by nemonemi** [comment] 2023-12-11 10:01
Due to the current workload, unfortunately not.

**Comment by brophdawg11** [comment] 2023-12-11 14:47
I'm afraid that the description above it a bit too vague to go on.  I'm going to close this out since we can't really look into it without a reproduction - but if you are able to provide one we will happily reopen it.

**Closed by brophdawg11** 2023-12-11 14:47 UTC
Labels: bug
