### ISSUE TITLE
useMatch in router v6 not working

### ISSUE THREAD

**Issue by DaliborTrampota** [remix-run/react-router#8876] opened 2022-05-16 20:30 UTC
I upgraded to v6 and now its not working at all

const matchCat = useMatch({ path: '/blogs/:category' })
    const matchID = useMatch({ path: '/blogs/:category/:id' })
    const fullMatch = useMatch({ path: '/blogs/:category/:id?' })
    console.log('cat', matchCat)
    console.log('id', matchID)
    console.log('full', fullMatch)
    console.log('loc', useLocation())
    
    
![image](https://user-images.githubusercontent.com/31895316/168677133-8c28eeda-737f-4aac-9904-ecb3e58591be.png)

_Originally posted by @DaliborTrampota in https://github.com/remix-run/react-router/issues/8870#issuecomment-1128105610_

**Comment by timdorr** [comment] 2022-05-17 01:26
Duplicate of #8381

**Closed by timdorr** 2022-05-17 01:26 UTC
