### ISSUE TITLE
[Bug]: useParams/matchRoutes is not properly decoding URLs

### ISSUE THREAD

**Issue by labkey-alan** [remix-run/react-router#11109] opened 2023-12-11 19:19 UTC
### What version of React Router are you using?

react-router-dom 6.20.1

### Steps to Reproduce

Have a Route in your app that looks something like:

```
<Route path=":myParam" element={<MyPage />} />
```

In the `MyPage` component use the `useParams` hook to get the `myParam` parameter:

```
const myParam = useParams().myParam;

console.log(myParam);
```

Then navigate to the following URL: `/bad%20%26%20encoding%20%25%20here`

### Expected Behavior

The parameter should be properly decoded as `"bad & encoding % here"`

### Actual Behavior

The parameter is not properly decoded, it is decoded as: `"bad %26 encoding % here"`

As far as I can tell this is because `matchRoutes` uses `safelyDecodeURI`, which uses `decodeURI` as seen [here](https://github.com/remix-run/react-router/blob/c47464c7e51c38cdf21a9fc2db81248daee2d171/packages/router/utils.ts#L496). Instead, it should be using `safelyDecodeURIComponent`, which uses `decodeURIComponent`.  The reason you want to use `decodeURIComponent` instead of `decodeURI` is that `decodeURIComponent` will decode characters that are part of the URI syntax, as documented [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI#decodeuri_vs._decodeuricomponent).

**Comment by timdorr** [comment] 2023-12-11 21:08
Duplicate of #10814

**Closed by timdorr** 2023-12-11 21:08 UTC
Labels: bug

**Comment by labkey-alan** [comment] 2023-12-11 23:06
Ah, yes that does look like a dupe, thank you!

**Comment by brophdawg11** [comment] 2024-01-26 19:03
(Cross-posting https://github.com/remix-run/react-router/issues/10814#issuecomment-1896598178 for visibility)

I've got a PR up to fix this in in #11199 but since path matching and encoding is such a tricky subject I'd love for a few folks to help alpha test the new approach 🙌 

I cut an experimental release with those changes - if anyone (OP or other) could test their specific scenario and let me know if it's fixed that would be super helpful in knowing we've got the right fix.

```
npm install react-router-dom@0.0.0-experimental-114cf0b7
```

I've also added the OP issue and the issue reported in #11179 to this code sandbox using the experimental release and things look good there: https://codesandbox.io/p/sandbox/billowing-fast-hv6v4v?file=%2Fsrc%2Findex.js%3A11%2C18

**Comment by labkey-alan** [comment] 2024-01-29 22:32
@brophdawg11 Thanks for looking into this issue. I'll try to get a test of this working locally and report back.

**Comment by labkey-alan** [comment] 2024-01-29 23:31
@brophdawg11 I have verified that version `0.0.0-experimental-114cf0b7` fixes the issue I encountered.
