### ISSUE TITLE
[v6-beta.4][Bug]: Custom routes no longer evaluated

### ISSUE THREAD

**Issue by MichielDeMey** [remix-run/react-router#8057] opened 2021-09-20 13:18 UTC
### What version of React Router are you using?

v6.0.0-beta.4

### Steps to Reproduce

We had a custom route `PrivateRoute` that basically just checked for a token to be available in the LocalStorage.
If it was not available, we would simply redirect to the login page.

```tsx
// PrivateRoute.tsx
const PrivateRoute: FC<RouteProps> = (props) => {
  debugger; // This is NOT hit on beta.4
  const { isAuthenticated } = useAuthentication(); // Context that returns authentication status

  if (!isAuthenticated) {
    return <Navigate to="/login" replace />;
  }

  return <Route {...props} />;
};
```

Implemented in our router :
```tsx
<Routes>
  <Route path="/" element={<p>Public Foo</p>} />
  <PrivateRoute path="/private" element={<p>Private Foo</p>} />
  <Route path="/login" element={<p>Some login</p>} />
</Routes>
```

This worked in `v6.0.0-beta.2`, but when upgrading to `v6.0.0-beta.4` the component was suddenly no longer evaluated. I've added a breakpoint in both versions and it's not hitting in `beta.4`, but it IS in `beta.2`.

Not sure if this is the way to customize routes since there is no official documentation yet regarding there custom routes.

### Expected Behavior

Custom route components are evaluated.

### Actual Behavior

Custom route components are no longer evaluated.

**Comment by timdorr** [comment] 2021-09-20 13:57
Duplicate of #8050

**Closed by timdorr** 2021-09-20 13:57 UTC
