### ISSUE TITLE
`preventScrollReset` doesn't do anything when `<ScrollRestoration getKey />` is defined

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#9977] opened 2023-01-25 01:30 UTC
### What version of React Router are you using?

6.7

### Steps to Reproduce

`<Link preventScrollReset />` works, but then add

```jsx
<ScrollRestoration getKey={(location) => location.pathname} />
```

And it restores the position even if `preventScrollReset` is defined.

### Expected Behavior

It shouldn't reset the scroll on link clicks.

### Actual Behavior

It resets the scroll on link clicks.

**Comment by ahmadspeechify** [comment] 2023-01-25 13:07
@brophdawg11 can I look into this?

**Comment by brophdawg11** [comment] 2023-01-25 15:04
This is expected behavior - scroll _restoration_ and _reset_ are two separate things.  We aways _restore_ scroll if we find a saved scroll position for the `key`.  If we do not find a saved position, then we _reset_ scroll back to the top.  `preventScrollReset` is only a mechanism to opt-out of the latter.

On normal push/replace `Link` navigations there is never anything to _restore_ since it's always a new `location.key` so `preventScrollReset` always comes into play.  Once you introduce `<ScrollRestoration getKey>` you've opted into _restoration_ on push/replace which can mean you don't even get to the _reset_ decision.  

To opt out of _restoration_ while using `getKey`, I would use `location.state`: https://stackblitz.com/edit/github-yfm8x5?file=src%2Fapp.tsx

**Comment by brophdawg11** [comment] 2023-01-25 20:06
Chatted with Ryan and closing this because it's working as expected.  His use case was doing something tricky where it wanted to restore on a different key based on `PUSH` versus `POP`, and that can be done in user-land with some usage of `useLocation`, `useNavigation`, `useNavigationType` etc. inside your `getKey` method

**Closed by brophdawg11** 2023-01-25 20:06 UTC
Labels: bug
