### ISSUE TITLE
[Feature]: Add state when navigate(-1) is used to go back 

### ISSUE THREAD

**Issue by RastogiAbhijeet** [remix-run/react-router#9491] opened 2022-10-23 06:27 UTC
### What is the new or updated feature that you are suggesting?

While the NavigationFunction allows going back in the history stack by simply calling `navigate(-1)`, currently it doesn't allow passing navigation options to the function args when number args are passed. 

TypeError

`Argument of type 'number' is not assignable to parameter of type 'To' `

### Why should this feature be included?

Introduction of this feature will allow the devs to simply move back in the history stack and pass state to prev routes. 
This can be especially helpful in scenarios where devs have to deal with form and show the same values in the prev routes.

**Comment by timdorr** [comment] 2022-10-24 03:01
Duplicate of #9403

https://github.com/remix-run/react-router/issues/9403#issuecomment-1268543266

**Closed by timdorr** 2022-10-24 03:01 UTC
Labels: feature
