### ISSUE TITLE
[Bug]: Attempted import error: 'startTransition' is not exported from 'react' (imported as 'React').

### ISSUE THREAD

**Issue by martinpyman** [remix-run/react-router#10574] opened 2023-06-08 12:22 UTC
### What version of React Router are you using?

6.12.0

### Steps to Reproduce

Hi There,

All my build relying on react-router-dom are failing with 
"Attempted import error: 'startTransition' is not exported from 'react' (imported as 'React')."

v6.4 is working as expected

Any help would be appreciated!

### Expected Behavior

Build to complete successfully

### Actual Behavior

Attempted import error: 'startTransition' is not exported from 'react' (imported as 'React').

**Comment by brophdawg11** [comment] 2023-06-08 13:11
Duplicate of https://github.com/remix-run/react-router/issues/10566

**Closed by brophdawg11** 2023-06-08 13:11 UTC
Labels: bug
