### ISSUE TITLE
[Feature]: Access History for Electron App

### ISSUE THREAD

**Issue by christianblandford** [remix-run/react-router#8451] opened 2021-12-07 18:51 UTC
### What is the new or updated feature that you are suggesting?

With v6, there is no way to get the history of HashRouter. 

I am using HashRouter to handle routing for my electron application. I need access to the history to determine the state of my back/forward buttons (disable back if no history, disable forward if at top of stack). 

Is there a way to do this?

### Why should this feature be included?

This would be helpful for anyone trying to use react-router-dom v6 with Electron applications.

**Comment by timdorr** [comment] 2021-12-07 19:11
Duplicate of #8264

**Comment by timdorr** [comment] 2021-12-07 19:12
Note: I know you're asking about a slightly different thing here, but resolving #8264 would also resolve this issue.

**Closed by timdorr** 2021-12-07 19:11 UTC
Labels: feature

**Comment by christianblandford** [comment] 2021-12-07 19:41
Thanks @timdorr This would definitely help me!
