### ISSUE TITLE
Splat Route's inside pathless layout routes break with `"-"` at the start of the URL

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#8561] opened 2022-01-05 19:41 UTC
### What version of React Router are you using?

v6

### Steps to Reproduce

https://stackblitz.com/edit/splat-route-dash-bug?file=src/App.tsx

```jsx
<Routes>
  <Route element={<Layout />}>
    <Route path="*" element={<Splat />} />
  </Route>
</Routes>
```

Visit `/-anything` that starts with a `"-"`.

### Expected Behavior

Splat route should render at `"/-splat"`

### Actual Behavior

Blank page, "no routes match" in the console.

Note that if you remove the pathless layout route above the splat it works fine.

**Comment by timdorr** [comment] 2022-01-06 04:21
Duplicate of #8525

Slight difference in the pattern, but essentially the same bug.

**Comment by timdorr** [comment] 2022-01-06 04:22
This patch may fix it: https://gist.github.com/kiliman/9b85e7873ed852d5ef0ea2f5af126b4b

**Closed** 2022-02-28 16:30 UTC
Labels: bug, accepted
