### ISSUE TITLE
[Bug]: <Outlet/> not working in build production with Vite.

### ISSUE THREAD

**Issue by vladimir-theunit** [remix-run/react-router#11517] opened 2024-05-01 09:06 UTC
### What version of React Router are you using?

^6.23

### Steps to Reproduce

I changed version to previous one ^6.21.3 and all works like needed. So inside my <Layout/> component is <Outlet/> But I don't see my home page. After decreasing version of react router all works like needed.

### Expected Behavior

Should render nested Routes.

### Actual Behavior

Outlet not working, so I don't see nested Routes

**Comment by brophdawg11** [comment] 2024-05-01 21:17
Could you provide a minimal reproduction of the issue?

**Comment by vladimir-theunit** [comment] 2024-05-02 06:56
> Could you provide a minimal reproduction of the issue?

Routing.tsx, all this code is inside <BrowserRouter>
`import { FC, lazy } from "react";
import { Navigate, Route, Routes, RouteProps } from "react-router-dom";
import { LazyPage, PrivateRoute } from "@/routes";
import { LoginPage, NotFoundPage } from "@/pages";
import { RoutersEnum } from "@/enums";
import Layout from "@/layouts/Layout";

// Import dynamic pages here
const HomePage = LazyPage(lazy(() => import("@/pages/Home")));
const PromotionsPage = LazyPage(lazy(() => import("@/pages/Promotions")));
const SocialAreaPage = LazyPage(lazy(() => import("@/pages/SocialArea")));
const GamesPage = LazyPage(lazy(() => import("@/pages/Games")));

const routes: RouteProps[] = [
  { path: RoutersEnum.PROMOTIONS, element: <PromotionsPage /> },
  { path: RoutersEnum.SOCIAL_AREA, element: <SocialAreaPage /> },
  { path: RoutersEnum.GAMES, element: <GamesPage /> },
] as const;

const Routing: FC = () => {
  return (
    <Routes>
      <Route element={<LoginPage />} path={RoutersEnum.LOGIN} />
      <Route element={<LoginPage />} path={RoutersEnum.SIGN_UP} />
      <Route path="/" element={<Layout />}>
        <Route
          index
          element={
            <>
              <PrivateRoute skipAuth />
              <HomePage />
            </>
          }
        />
        <Route element={<PrivateRoute />}>
          {routes.map((route) => {
            return <Route key={route.path} {...route} />;
          })}
        </Route>
        <Route path="*" element={<Navigate to="/404" />} />
        <Route path="/404" element={<NotFoundPage />} />
      </Route>
    </Routes>
  );
};

export default Routing;
`

After reaching the home page, I only see the layout without the homepage content, but inside the layout, the PrivateRoute contains the Outlet, so don't worry.

After downgrading the version of react-router-dom, all my routes work as expected, as I mentioned in the previous message. While debugging, I noticed that the Outlet isn't functioning in latest version.

I'm using Vite and React with TypeScript. The router only fails to work when I build for production and preview it.

**Comment by mohammad-aljamil** [comment] 2024-05-02 12:15
solved in https://github.com/remix-run/react-router/issues/11480#issuecomment-2068291310

**Comment by brophdawg11** [comment] 2024-05-02 12:40
Yeah my guess is this is due to the bad rollup version - please ensure vite is using the latest version of rollup and the issue should be resolved (see the comments in #11480 for how to do this).  Closing this as a duplicate.

**Closed by brophdawg11** 2024-05-02 12:40 UTC
Labels: bug
