### ISSUE TITLE
Submitting forms in parent layout routes tries posting to wrong action.

### ISSUE THREAD

**Issue by MoSattler** [remix-run/react-router#11024] opened 2023-11-12 11:55 UTC
### What version of Remix are you using?

2.2.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

I have a layout route on
`my-parent.$someParam.tsx`
which adds a form and a action to handle the form. 

inside that route there are three children:
- `my-parent._index.tsx`
- `my-parent.$someParam.my-child.tsx`
- `my-parent.$someParam.my-child._index.tsx`

Now, when I am submitting the form on `/my-parent/some-value/my-child`, everything works as expected. 

But if I am on `/my-parent/some-value/my-child?index`, and I try submit, I get the following error: 
> 405 Error: Route "routes/my-parent._index.tsx" does not have an action, but you are trying to submit to it. To fix this, please add an action function to the route.

### Expected Behavior

Forms should always submit to the action in their route, not some other route

### Actual Behavior

For some reason, if i am on the `?index` path of some child route, actions of parent layout routes also try to post on their respective index routes

**Comment by brophdawg11** [comment] 2023-11-14 14:08
Thanks for the reproduction!  This looks like it's a bug in `useFormAction` that shows up after you've submitted to a separate child index `action`.  This is fixed by #11025 and will be available in the next release 👍

**Closed by brophdawg11** 2023-11-14 14:08 UTC
