### ISSUE TITLE
[Bug]: Module not found: Error: Can't resolve '@remix-run/router'

### ISSUE THREAD

**Issue by DiFuks** [remix-run/react-router#9317] opened 2022-09-21 10:25 UTC
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

In the Yarn PNP mode, start the build of the application with the react-router-dom

### Expected Behavior

The build is successfully completed

### Actual Behavior

Getting error because @remix-run/router is not listed in dev or peer dependencies of react-router-dom

**Comment by timdorr** [comment] 2022-09-21 17:26
Duplicate of #9243

This will be fixed in the next release.

**Closed by timdorr** 2022-09-21 17:26 UTC
Labels: bug
