### ISSUE TITLE
[Bug]: HashRouter: Changing URL in browser doesn't navigate if navigation is blocked via history.block()

### ISSUE THREAD

**Issue by antonabramovich** [remix-run/react-router#8744] opened 2022-03-29 15:17 UTC
### What version of React Router are you using?

6.2.2

### Steps to Reproduce

1. Navigate to a route which blocks the navigation via "history.block()". Blocker function allows navigation instantaneously, based on some provided condition, without prompting the user in any way.
2. Try changing the URL in the browser bar manually, say, to a home page.

Demo: https://stackblitz.com/edit/react-ts-eyafwn?file=index.tsx
P.S. BrowserRouter works as expected

### Expected Behavior

Blocker function is triggered (and, as a result, navigation happens, if blocker allows)

### Actual Behavior

Browser URL is changed, but actual navigation isn't happening, blocker function is not called (no confirm modal)

**Comment by timdorr** [comment] 2022-03-29 16:52
This is essentially a duplicate of #8139. We need those APIs added back to support this kind of behavior in a React-compatible way.

**Closed by timdorr** 2022-03-29 16:52 UTC
Labels: bug
