### ISSUE TITLE
[Bug]: [v6] Not rendering custom components inside <Routes>

### ISSUE THREAD

**Issue by sjbuysse** [remix-run/react-router#8066] opened 2021-09-23 09:15 UTC
### What version of React Router are you using?

6.0.0-beta.4

### Steps to Reproduce

```
type Props = {
  path: string;
  loginPath: string;
  element: React.ReactElement
} & RouteProps;

const ProtectedRoute = ({loginPath, element, ...routeProps}: Props) => {
  console.log('mounted')
  const {isAuthenticated} = useAuth();
  return (<Route  {...routeProps} element={isAuthenticated() ? element : <Navigate to={loginPath}/>}/>)
}

export function App() {
  return (
        <Routes>
          <ProtectedRoute path={'/dashboard'} loginPath={'/login'} element={<span>Dashboard</span>}/>
          <Route path='/login' element={<span>login</span>}/>
        </Routes>
  );
};
```

### Expected Behavior

when going to '/dashboard', the `ProtectedRoute` component is rendered, and I can see a console log that says 'mounted'.

### Actual Behavior

The component will never be rendered/mounted. There is also no `console.log` executed. It will actually render the `element` prop instead (`<span>Dashboard</span>`)

This used to work in 6.0.0-beta.0

**Comment by MeiKatz** [comment] 2021-09-23 09:28
This feature known from Reach Router was drop in one of the last patch versions.

**Comment by sjbuysse** [comment] 2021-09-23 09:31
@MeiKatz , so this is wanted behaviour? I know this is not a suggestion board, but any advice on implementing a Private Route without this feature (and without using object routes)?

**Comment by MeiKatz** [comment] 2021-09-23 09:33
@sjbuysse Yes, it is wanted behaviour. `<Route />` components are only stub components that can be read by the `<Routes />` component. You can implement the wanted behaviour with something like the following (not tested):

```jsx
function PrivateRoute({
  children,
  loginPath
}) {
  console.log('mounted')
  const { isAuthenticated } = useAuth();

  if ( isAuthenticated ) {
    return children;
  }
  
  return (
    <Navigate to={ loginPath } />
  );
}

<Route path="/dashboard" element={
  <PrivateRoute loginPath="/login">
    <span>Dashboard</span>
  </PrivateRoute>
} />

**Comment by wojtekmaj** [comment] 2021-09-23 09:53
Duplicate of #8033. I suggested in #8063 to improve the developer experience around that matter so that these issue reports don't keep coming back but unfortunately RR team doesn't seem to be interested.

**Closed** 2021-09-23 11:27 UTC

**Comment by negyxo** [comment] 2021-12-08 03:38
OK, I understand the change, but what's the solution if we want to wrap the "path" properties to something more meaningful than string on RouteProps? This applies, of course, when using Typescript. For instance, I used wrapping to change string type to string literals in Typescript, for instnace:

`type RouteTemp = Omit<RouteProps, "path">;

interface RoutePropsEx extends RouteTemp {
    path: RoutePart;
}

export const RouteEx = (props: RoutePropsEx) => <Route {...props} />;`

Now if RoutePart is defined like:
`type RoutePart = "/home" | "dashboard" | etc.`

then, specifying path will be strictly determined.
