### ISSUE TITLE
[Bug]: Layout CSS file is removed after clicking on an anchor link

### ISSUE THREAD

**Issue by yuval-shimoni-hunters** [remix-run/react-router#12372] opened 2024-11-24 09:42 UTC
### What version of React Router are you using?

v7

### Steps to Reproduce

1) Open react-router docs
2) Click on some anchor link

https://www.loom.com/share/82ba7a8210554a02821a9488d829dd1a?sid=246e8bfb-36a0-4596-ad64-64c252c4fee1

### Expected Behavior

Refer to the relevant section with its normal styling.

### Actual Behavior

All the styles are removed, and the document’s text appears unformatted and messy.

**Comment by timdorr** [comment] 2024-11-24 16:12
Duplicate of #12365

**Closed by timdorr** 2024-11-24 16:12 UTC
Labels: bug
