### ISSUE TITLE
[Bug]: `setSearchParams` from `useSearchParams` discards intermediate result from pure updaters.

### ISSUE THREAD

**Issue by weiwei-lin** [remix-run/react-router#10799] opened 2023-08-21 04:16 UTC
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

```
const [searchParams, setSearchParams] = useSeachParams();

...

setSearchParams((prevState) => {
  // Create a copy of `prevState` to keep the updater function pure.
  const nextState = new URLSearchParams(prevState);
  nextState.set('key1', 'val1');
  return nextState;
});

setSearchParams((prevState) => {
  // Create a copy of `prevState` to keep the updater function pure.
  const nextState = new URLSearchParams(prevState);
  nextState.set('key2', 'val2');
  return nextState;
});

setSearchParams((prevState) => {
  // Create a copy of `prevState` to keep the updater function pure.
  const nextState = new URLSearchParams(prevState);
  nextState.set('key3', 'val3');
  return nextState;
});


```

### Expected Behavior

all three keys should have value assigned to them.
i.e. `searchParams.toString() === 'key1=val1&key2=val2&key3=val3'`

### Actual Behavior

only the last key have value assigned to them.
i.e. `searchParams.toString() === 'key3=val3'`

results from intermediate updaters are discarded.

**Comment by weiwei-lin** [comment] 2023-08-21 04:22
The workaround is to keep the function impure.
But this is counter-intuitive because
1. this is different from `setState` from `useState`, and
2. the updater function's type definition is `(prev: URLSearchParams) => URLSearchParamsInit`, which suggests the previous state shall be received, and
3. making the update impure is generally speaking a bad practice.

**Comment by timdorr** [comment] 2023-08-21 14:53
Duplicate of #9757

**Closed by timdorr** 2023-08-21 14:53 UTC
Labels: bug
