### ISSUE TITLE
[v6] [Bug]: URI encoded params sometimes fail to match in <Routes>

### ISSUE THREAD

**Issue by thedanwoods** [remix-run/react-router#8109] opened 2021-10-05 12:44 UTC
### What version of React Router are you using?

6.0.0-beta.5

### Steps to Reproduce

In some circumstances `<Routes>` or `useRoutes` is not matching deeper routes when the params are URI encoded.

This seems to be caused by a bug in [the new getPathnameStart function](https://github.com/remix-run/react-router/blob/80492b9214271491881fabb2c7558ce180e892a1/packages/react-router/index.tsx#L1197). It's using the length of the `params` to work out where to trim the `pathname`. But `params` has already been URI decoded, whereas the `pathname` has not, so the `.length` is not reliable.

Repro at [https://codesandbox.io/s/happy-villani-nee76?file=/src/App.js](https://codesandbox.io/s/happy-villani-nee76?file=/src/App.js). Click on the "Item with id of ::" link and it doesn't render. If you downgrade to 6.0.0-beta.4 it works as expected.

### Expected Behavior

In the codesandbox, /items/abc/%3A%3A should render the `<SingleItem />` component.

### Actual Behavior

It matches /items/abc/%3A and /items/abc/hi, but not /items/abc/%3A%3A.

**Comment by mjackson** [comment] 2021-10-05 16:23
Thanks for the report. I'm pretty sure this is a duplicate of #8072, which I'm working on fixing this week. Should be fixed in the next beta release.

**Closed by mjackson** 2021-10-05 16:23 UTC
