### ISSUE TITLE
[Bug][v6]: Could not use wrapper component around Route

### ISSUE THREAD

**Issue by rcadelw33** [remix-run/react-router#8050] opened 2021-09-17 08:48 UTC
### What version of React Router are you using?

6.0.0-beta.4

### Steps to Reproduce

- Use version 6.0.0-beta.4

- Create wrapper component around Route

You can check it on this codesanbox
https://codesandbox.io/s/react-router-forked-q8dwu?file=/index.js

in this example MyRoute is not render so console.log is not called but Route is actually render so the problem is not visible in UI

### Expected Behavior

Wrapper component should be render

### Actual Behavior

Props seems to be passed down to original Route Component

**Comment by changesbyjames** [comment] 2021-09-17 10:53
I just ran into this problem as well. I'm seeing something even stranger where any component with a `path` and `element` property is being treated as a route.

https://codesandbox.io/s/react-router-forked-0nt2q

Does this mean it's impossible to create custom behaviour for routes?

**Comment by charlesomer** [comment] 2021-09-17 22:48
https://github.com/remix-run/react-router/issues/8033

Looks like React Router will now only render exact `<Route>` components under `<Routes>` which might explain what's going on here :/ Although there should probably be some sort of warning somewhere

**Comment by timdorr** [comment] 2021-09-18 01:31
Yeah, this is a duplicate of #8033. Please see this comment: https://github.com/remix-run/react-router/issues/8033#issuecomment-918447523

**Closed by timdorr** 2021-09-18 01:31 UTC

**Comment by charlesomer** [comment] 2021-09-18 07:00
Is there an example for how private routes or similar are now supposed to be done?

**Comment by wojtekmaj** [comment] 2021-09-22 14:46
Here's my suggestion for how to build private routes for now: .

```diff
import { Navigate } from 'react-router';

-export default function AuthRoute({ element, ...otherProps }) {
+export default function WithAuth({ element }) {
  const isAuthenticated = useIsAuthenticated(); // Implementation up to you

- return (
-   <Route 
-     {...otherProps}
-     element={isAuthenticated ? element : (
-       <Navigate to="/login" />
-     )}
-   />
- );
+ return isAuthenticated ? element : (
+  <Navigate to="/login" />
+ );
}
```

Usage:

```diff
  <Routes>
    <Route path="/" element={<p>Home</p>} />
    <Route path="/login" element={<p>Login</p>} />
-   <AuthRoute path="/profile" element={<p>Profile</p>} />
+   <Route path="/profile" element={<WithAuth element={<p>Profile</p>} />} />
  </Routes>
```

Demo:
https://codesandbox.io/s/react-router-6-beta-4-auth-route-ni5gh?file=/src/App.js

**Comment by charlesomer** [comment] 2021-09-22 14:53
Yeah that’s pretty much what I have above by the looks of it :/ Just seems kind of messy

**Comment by changesbyjames** [comment] 2021-09-22 15:14
I've found using the new `<Outlet />` gets you a much neater solution.

```tsx
export const AuthenticationGate: FC<AuthenticatedProps> = () => {
  const isAuthenticated = useIsAuthenticated();

  // If the user is not authenticated, redirect them to a logon page
  if (!isAuthenticated) {
    return <Navigate to="/login" />
  }
  
  // If they're a user, go ahead and continue to what they wanted to see
  return <Outlet />
}
```

```tsx
const App: FC = () => {

  return <BrowserRouter>
    <Routes>
      <Route element={<AuthenticationGate />}>
        <Route path="/" element={<NeedsAuthentication />} />
      </Route>
      <Route path="/login" element={<Login />} />
      <Route path="/logout" element={<Logout />} />
      <Route path="/logout/callback" element={<PostLogout />} />
      <Route path="/signin-oidc" element={<Redirect />} />
      <Route path="*" element={<NotFound />} />
    </Routes>
  </BrowserRouter>
}
```

It is more hierarchical then just being able to drop in a custom route but it works well for me.

**Comment by wojtekmaj** [comment] 2021-09-23 10:33
I really like your idea @changesbyjames But it seems like it's breaking nested Routes for me, so that's not an option. Gate it is then! 😕
