### ISSUE TITLE
Remove trailing slash from match.url

### ISSUE THREAD

**Issue by shawnmclean** [remix-run/react-router#4841] opened 2017-03-26 10:54 UTC
## Version
4.0.0

## Test Case
https://reacttraining.com/react-router/web/example/recursive-paths

## Steps to reproduce
In the mini browser, put a trailing slash after a resource like: `/3/`

## Expected Behavior
nested url should look like `/3/2`

## Actual Behavior
nested url looks like `/3//2`

Is this something thats possible?

**Comment by pshrmn** [comment] 2017-03-26 16:41
That is what the `strict` prop is for. I'm not in a position to test it right now, but I believe that that would fix the recursive example. Anyways, once relative path support is merged in, this will be moot for most users since React Router will handle the path joining for them.

**Comment by shawnmclean** [comment] 2017-03-26 19:28
The `strict` didn't help my case because I'd need to support both trailing and non trailing slash. This does have to do with relative paths. So for now, I'm removing the trailing slash from `match.url` when combining it with my relative path. This is messy but will have to do until your PR is merged in. Any plans to fix the merge conflicts and merge it in?

**Comment by pshrmn** [comment] 2017-03-26 20:44
Relative `<Route>`s and `<Link>`s should happen at the same time (probably a short beta to verify they work as expected). I have the code rebased, but I am waiting on a decision for what to do when the parent match is `null` (caused by using `<Route children>`) before moving forward.

For the time being I would just use

```js
const join = (base, path) => {
  return base.charAt(base.length-1) === '/'
    ? base.slice(0, -1) + path
    : base + '/' + path
}

<Route path={join(match.url, '/rest')} component={Rest} />
```

**Comment by otbe** [comment] 2017-06-20 20:51
Very unexpected behavior at a first glance. Some guidance would be nice :)

We use a lot of this ```<Link to={`${match.url}/foo`}>Foo</Link>``` which will result in ```example.com/bar/foo``` or ```example.com/bar//foo``` whether you use ```example.com/bar``` or  ```example.com/bar/```

**Comment by robmoorman** [comment] 2017-06-28 17:24
Experiencing the same unpredictable route match.url trailing slashes, especially with nested routes

**Comment by filoxo** [comment] 2017-11-14 17:23
I solved this at the parent route level by redirecting to the no-slash-url. 

```
<Switch>
  <Redirect strict from={url + '/'} to={url} />
  <Route path={url} component={App} />
</Switch>
```

This way the url matched never contains the trailing slash. Just another option.

**Comment by tomachinz** [comment] 2017-12-04 03:17
Yeah I'd like some guidance. Should I be aiming to have slashes at end or not? Coming from WordPress the answer is yes I'd like a / at the end of everything. As I began to re-work my code to support that I begin to see example.com/bar//foo as well, making me think no trailing slash is the standard with React.

**Comment by leite08** [comment] 2017-12-04 20:35
I struggled for quite some time to get a workaround for this.

I also learned about `strict`, but as @shawnmclean mentioned, it doesn't fix the main issue here: to configure React Router (RR) to remove the trailing slash at the end of the URL by default.

This comment on a strict-related issue worked for me:
https://github.com/ReactTraining/react-router/issues/4170#issuecomment-269795053

Our structure ended up like this:

```
const RemoveTrailingSlash = ({location}) => {
...
}
...
<Router>
      <Navigation {...props} />
      <Route path="/" render={RemoveTrailingSlash} />
      <Grid>
        <Switch>
          <Route...
```

I really suggest there is a configuration on RR that would remove all the trailing slashes on URLs.

Hope this comment can help people looking for this.

**Comment by todesstoss** [comment] 2017-12-20 11:20
@leite08 thanks for the solution, it works for most cases. But when I have top-level `<Route>` component with multilingual configuration, e.g `path="/:lang(en|it)?"` and try to use `<Link to={`${match.url}/foo`}` so URL could respect the current matched language, it works only if lang param is not omitted e.g: `site.com/en/foo`, but for default case, I end up with a URLs like this: `site.com//foo`.

**Comment by hazelsparrow** [comment] 2018-03-08 15:42
Having two routes -- the first being `strict` and `exact` and the other being a fallback route -- solves the problem.

```
      <Redirect strict exact from={match.path} to={`${match.url}/foo`} />
      <Redirect exact from={match.path} to={`${match.url}foo`} />
```

Any thoughts on potential problems/caveats?

**Comment by inoyakaigor** [comment] 2018-10-19 14:42
I think trailing slash should be removed from match.url. This behavior is not obvious and should be clarified in documentation

**Comment by tomachinz** [comment] 2018-10-22 06:56
It is also "Not The Unix Way" of doing things to use /something when it's not at root.

**Comment by tomachinz** [comment] 2018-10-22 06:58
> Having two routes -- the first being `strict` and `exact` and the other being a fallback route -- solves the problem.
> 
> ```
>       <Redirect strict exact from={match.path} to={`${match.url}/foo`} />
>       <Redirect exact from={match.path} to={`${match.url}foo`} />
> ```
> Any thoughts on potential problems/caveats?

This is good I will use this double spec approach if my troubles come again.

**Comment by hilo2120** [comment] 2019-06-11 06:33
I'm facing the same problem,
I solved it in main App Switch Component using regex to delete any trailing slash from all paths
`
const pathname = window.location.pathname
...
<Switch>
     {(/\/$/).test(pathname) &&
          <Redirect to={pathname.slice(0, -1)} />
     }
     <PrivateRoute path={'/'} exact component={Dashboard}/>
     <Route path={'/login'} exact component={Account}/>
</Switch>
`
It's working now but looks a little not right!

**Comment by Pau1fitz** [comment] 2019-07-01 19:48
I just did something like this:

```
const uri = `/test/${id}`;
// remove trailing slash from url
uri.replace(/\/+$/, '');
```

**Comment by dylanwulf** [comment] 2019-08-05 19:44
I was using @filoxo 's solution, but it recently stopped working in the 5.0.1 release

**Comment by LAITONEN** [comment] 2019-08-21 16:46
Any progress?

**Comment by jrrdev** [comment] 2019-08-21 19:59
> I was using @filoxo 's solution, but it recently stopped working in the 5.0.1 release

@dylanwulf You can try to use the following code, it works for me with the 5.0.1 release :

```jsx
<Switch>
  {/* Removes trailing slashes */}
  <Route
    path="/:url*(/+)"
    exact
    strict
    render={({ location }) => (
      <Redirect to={location.pathname.replace(/\/+$/, "")} />
    )}
  />
  {/* Removes duplicate slashes in the middle of the URL */}
  <Route
    path="/:url(.*//+.*)"
    exact
    strict
    render={({ match }) => (
      <Redirect to={`/${match.params.url.replace(/\/\/+/, "/")}`} />
    )}
  />
```

A little bit hackish but I get correcting routing also with:
* `/foo/////bar`
* `/foo/bar///`

**Comment by HosseinAlipour** [comment] 2019-09-05 19:18
I used the following code in my main component I define the router, but I'm not sure If this is the best practice for React Router

``` javascript
  if (props.location.pathname.endsWith('/')) {
    props.location.pathname = props.location.pathname.slice(0, -1);
  }
```

**Comment by Ovi** [comment] 2019-09-17 09:25
I did a workaround:

```js
export const path = url => {
  const fixedPath = url.endsWith('/')
    ? path(url.substring(0, url.length - 1))
    : url;

  return fixedPath;
};
```

then:

```jsx
<Redirect to={path('/dashboard/')} />
// returns => /dashboard

<Redirect to={path('/dashboard///')} />
// returns => /dashboard
```

**Comment by divonelnc** [comment] 2019-10-23 12:30
I tried the workarounds above that detect the trailing '/' and fix it with a `<Redirect/>` but  they triggered **a page reload at every redirect**. 

To fix that I used this code instead:

```
const pathname = window.location.pathname;
if(pathname !== "/" && (/\/$/).test(pathname)){
    props.history.replace(pathname.slice(0, -1));
}
```

Using replace removed the trailing space without reloading the page.

**Comment by HosseinAlipour** [comment] 2019-10-23 17:26
@divonelnc, did check for other browsers?

**Comment by divonelnc** [comment] 2019-10-24 08:43
@HosseinAlipour Tested on Chrome, Firefox, and Edge so far. Any reason why it wouldn't work on some browsers?

**Comment by inoyakaigor** [comment] 2019-12-23 10:36
This issue is not a stale stupid bot

**Comment by rollacaster** [comment] 2020-03-23 12:53
I am not sure if this is related but I fixed the my trailing slash issues by changing my `webpack` config.

If I started `webpack-dev-server` within my `/src` and if one of the folder names with my `/src` clashed with a route name I got an additional trailing slash after a browser refresh.

I started `webpack-dev-server` in another folder and it worked fine.

**Comment by bertho-zero** [comment] 2020-04-21 09:05
My problem is that if my nested routes are in a parent route like `/supervisor` it works, if my parent route is `''` then it becomes `'/'` with `useRouteMatch`.

My workaround:

```jsx
const { path, url } = useRouteMatch();

<Link to={`${url.endsWith('/') ? url.slice(0, -1) : url}/announcement`} />

<Route path={`${path.endsWith('/') ? path.slice(0, -1) : path}/announcement`} />
```

**Comment by RhysTowey** [comment] 2020-04-21 17:11
Adding a `<Redirect>` is the cleanest solution I could find

```
function App() {
    const { pathname } = useLocation();
    return (
        <div>
            <Switch>
                <Redirect from="/:url*(/+)" to={pathname.slice(0, -1)} />
                <Route exact path="/" component={Home} />
                <Route path="/test-page" component={TestPage} />
            </Switch>
        </div>
    );
}
```
Credit to: [https://jasonwatmore.com/post/2020/03/23/react-router-remove-trailing-slash-from-urls](url)

**Comment by bertho-zero** [comment] 2020-04-22 09:29
It is not enough to build `Link`s and `Route`s in the nested routes.

`useRouteMatch` continues to return a slash for `path` and `url` instead of an empty string, which does not allow to construct an url like that:

```js
`${url}/announcement`
```

**Comment by Akatsukac** [comment] 2020-05-12 16:49
>                 <Redirect from="/:url*(/+)" to={pathname.slice(0, -1)} />

Hey just want to let you know that navigating to something like /hello//world with this redirect pattern results in the url being rewritten in an unexpected manner and this results in an error. I would not recommend using this solution.

**Comment by bertho-zero** [comment] 2020-05-13 08:02
There is no need to navigate to a url ending in `/`, if the url is `''` then it becomes automatically and in any case `'/'`, which is annoying for composing sub-routes.

In my case it works perfectly if I have `/prefix`, for example, but in my storybook without 'base' it doesn't work.

**Comment by Akatsukac** [comment] 2020-05-13 16:08
> > I was using @filoxo 's solution, but it recently stopped working in the 5.0.1 release
> 
> @dylanwulf You can try to use the following code, it works for me with the 5.0.1 release :
> 
> ```js-jsx
> <Switch>
>   {/* Removes trailing slashes */}
>   <Route
>     path="/:url*(/+)"
>     exact
>     strict
>     render={({ location }) => (
>       <Redirect to={location.pathname.replace(/\/+$/, "")} />
>     )}
>   />
>   {/* Removes duplicate slashes in the middle of the URL */}
>   <Route
>     path="/:url(.*//+.*)"
>     exact
>     strict
>     render={({ match }) => (
>       <Redirect to={`/${match.params.url.replace(/\/\/+/, "/")}`} />
>     )}
>   />
> ```
> 
> A little bit hackish but I get correcting routing also with:
> 
> * `/foo/////bar`
> * `/foo/bar///`

For those interested in leveraging redirects, here's a slight improvement on remove extra slashes:
{/* Removes duplicate slashes */}
<Route exact strict path="(.*//+.*)" render={({ location }) => <Redirect to={location.pathname.replace(/\/\/+/g, '/')} />} />

This handles cases where you have extra slashes at the beginning, middle, or end and makes all replacements at once so you don't have to chain redirects (ie ///hello//world//url -> /hello//world//url -> /hello/world//url -> /hello/world/url).

+1 on the approach to removing the trailing slash that the original post gave.

**Comment by Bielik20** [comment] 2021-01-13 11:39
I also did change replace value from `''` to `location.search` so that we do not loose query params:

```tsx
export const RemoveTrailingSlash: React.FC = () => {
  return (
    <Switch>
      <Route
        path="/:url*(/+)"
        exact
        strict
        render={({ location }) => <Redirect to={location.pathname.replace(/\/+$/, location.search)} />}
      />
    </Switch>
  );
};
```

**Comment by sahil-ag** [comment] 2021-04-07 09:53
> For those interested in leveraging redirects, here's a slight improvement on removing all extra slashes:
> 
> ```
> {/* Removes duplicate slashes */}
> <Route exact strict path="(.*//+.*)" render={({ location }) => <Redirect to={location.pathname.replace(/\/\/+/g, '/')} />} />
> ```
> 
> This handles cases where you have extra slashes at the beginning, middle, or end and makes all replacements at once so you don't have to chain redirects (ie ///hello//world//url -> /hello//world//url -> /hello/world//url -> /hello/world/url).

Modified this a little to keep the URL same - 
```js
<Redirect
    exact
    strict
    from="(.*//+.*)"
    to={location.pathname.replace(/\/\/+/g, '/') + window.location.search + window.location.hash}
/>
```

This also ends up handling URLs like - `//hello/world?a=123#112`  or `///hello/world?a=123#112` and hence can be added without any issues.

**Comment by Ovi** [comment] 2021-04-07 12:09
No updates yet?
It's been 4 years now 🙄

**Comment by mleister97** [comment] 2021-04-18 12:02
Adding the following to the top of your routes-file should work:

```js
<Redirect from="/:url*(/+)" to={window.location.pathname.replace(/\/+$/, window.location.search)} />
```

Note: As the routes are probably close to the root in the dom tree I would not consider using any react-router hook as It will cause this element to rerender every time the url changes.

**Comment by Archivec** [comment] 2021-08-13 07:22
>  <Redirect strict from={url + '/'} to={url} />
This would require the exact parameter to not redirect all subsequent path that follows

**Comment by chaance** [comment] 2021-09-05 23:06
Maybe I'm missing something here, so feel free to correct me if so, but this feels like it should be solvable with a relatively simple function.

```tsx
function Component() {
  let { url } = useRouteMatch();
  let { id } = useParams();
  return (
    <Route path={joinPaths(url, id)} component={View} />
  );
}

function joinPaths(...segments) {
  return segments.join('/').replace(/\/+/g, '/');
}
```

We could do this internally (unlikely with <= v5 since it's a breaking change) or expose it as a helper, but is this not sufficient?

**Comment by MeiKatz** [comment] 2021-09-06 07:02
@chaance this is a good work-around. But it is a work-around and it should be done without it. Therefore it should be a basic behaviour of RR without the need to think about it.

**Comment by chaance** [comment] 2021-09-06 15:34
I'm not 100% sure that I agree. `match.url` is correct here. Cleaning up the value that you provide to either `useRouteMatch` or `Route` means we have to make assumptions about your app that might not be true for others.

If trailing slashes aren't important to you, you can always compose our `useMatch` or `useRouteMatch`:

```tsx
import { useRouteMatch as useRouteMatch_ } from "react-router";

export function useRouteMatch(path) {
  return useRouteMatch_(trimTrailingSlashes(path));
}
```

**Comment by MeiKatz** [comment] 2021-09-06 16:26
Why not add a default behaviour and if this default behaviour doesn't match what a developer wants he/she can disable it? I think in the most cases triming slashes is exactly what you want.

**Comment by chaance** [comment] 2021-09-06 17:05
We could certainly discuss something like that for v6, but at least in v4/v5 changing the default behavior would be a breaking change. @mleister97 is correct that this is currently the intended behavior, so I'd suggest adopting one of the workarounds for now.

**Comment by chaance** [comment] 2021-09-06 17:09
Closing this, but see https://github.com/remix-run/react-router/discussions/8022 to pick up on potential changes for v6.

**Closed by chaance** 2021-09-06 17:09 UTC
Labels: fresh

**Comment by tomachinz** [comment] 2021-09-10 17:31
There is some nice solutions here posted. I'm happy with these. For me it was more of a spiritual thing - a test of how I felt about React router. These are good enough for me.

**Comment by erdum** [comment] 2022-09-22 06:24
**I solved like this:**

1. Put base tag at the top of your head tag inside your public/index.html `<base href="%PUBLIC_URL%">`
2. Give relative paths to all of your assets `<link rel="stylesheet" href="./assets/foo.min.css">`
3. Put assets folder inside your src folder
4. Set homepage field in your package.json `"homepage": "/",`
5. (If you are using react-router and you want to remove trailing slashes) 
```
import * as React from "react";
import { useLocation, Navigate } from "react-router-dom";

const RemoveTrailingSlash = () => {
  const location = useLocation();
  
  return (
    <>
      {location.pathname.match(/.*\/$/) ? (
        <Navigate
	  to={{
	    pathname: location.pathname.replace(/\/+$/, ""),
	    search: location.search,
	  }}
	/>
      ) : null}
    </>
  );
};

export default RemoveTrailingSlash;
```
consume this component inside your BrowserRouter
```
<BrowserRouter>
  ...
  <RemoveTrailingSlash />
  ...
</BrowserRouter>
```

> Note: this is not a guaranteed solution I am sharing this solution because it worked for me.
