### ISSUE TITLE
[Bug]: Statically defined loader isn't running in parallel with the lazy function

### ISSUE THREAD

**Issue by erism** [remix-run/react-router#10275] opened 2023-03-28 12:42 UTC
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

Crate a route with lazy and loader definition.
Add delays and console logs to both lazy and loader definitions in order to inspect running order.

[Example codesandbox](https://codesandbox.io/s/cold-frog-4nzpdj?file=/src/App.tsx)

### Expected Behavior

Loader function should run in parallel with lazy according to the docs:
https://reactrouter.com/en/main/route/lazy#statically-defined-properties

According to the [example codesandbox](https://codesandbox.io/s/cold-frog-4nzpdj?file=/src/App.tsx), running order should be (visible on console):
-Lazy import begin 
-loader begin
-loader end
-Lazy import end

### Actual Behavior

Loader function starts after lazy function finishes. Running order is:
-Lazy import begin 
-Lazy import end
-loader begin
-loader end

**Comment by brophdawg11** [comment] 2023-03-29 18:56
Ah this is actually the same root cause as https://github.com/remix-run/react-router/issues/10194 and was fixed by https://github.com/remix-run/react-router/pull/10201.  That's available in `6.10.0-pre.2` currently and should be out in a stable 6.10.0 shortly.

**Comment by brophdawg11** [comment] 2023-03-29 20:29
I think this should be resolved in `6.10.0` now

**Closed by brophdawg11** 2023-03-29 20:29 UTC
Labels: bug, awaiting release
