### ISSUE TITLE
[Bug]: repetitive rendering

### ISSUE THREAD

**Issue by guaijie** [remix-run/react-router#9176] opened 2022-08-20 12:27 UTC
### What version of React Router are you using?

16.8

### Steps to Reproduce

useNagative will affect a repetitive rendering

```ts
import { useMemo, useRef } from 'react';
import { isFunction } from '../utils';

type noop = (this: any, ...args: any[]) => any;

type PickFunction<T extends noop> = (
  this: ThisParameterType<T>,
  ...args: Parameters<T>
) => ReturnType<T>;

function useMemoizedFn<T extends noop>(fn: T) {
  if (process.env.NODE_ENV === 'development') {
    if (!isFunction(fn)) {
      console.error(`useMemoizedFn expected parameter is a function, got ${typeof fn}`);
    }
  }

  const fnRef = useRef<T>(fn);

  // why not write `fnRef.current = fn`?
  // https://github.com/alibaba/hooks/issues/728
  fnRef.current = useMemo(() => fn, [fn]);

  const memoizedFn = useRef<PickFunction<T>>();
  if (!memoizedFn.current) {
    memoizedFn.current = function (this, ...args) {
      return fnRef.current.apply(this, args);
    };
  }

  return memoizedFn.current as T;
}
```
Consider using 'memoizedFn' cache 'Navigate' in your internal implementation

### Expected Behavior

useNagative will  not affect a repetitive rendering

### Actual Behavior

useNagative will affect a repetitive rendering

**Comment by jamesarosen** [comment] 2022-08-21 00:15
I'm experiencing the same. Here's a hook that demonstrates the behavior:
```tsx
import { useLocation, useNavigate } from "@remix-run/react";
import { useEffect } from "react";

type StringMap = { [key: string]: string };

/**
 * Applies default query-params, using history.replaceState to replace the
 * current path & query with a new one with the defaults applied explicitly.
 * @param defaults
 * @return params with defaults applied
 */
export default function useDefaultParams(defaults: StringMap): StringMap {
  const location = useLocation();
  const navigate = useNavigate();

  const search = new URLSearchParams(location.search);

  useEffect(() => {
    let needsReplace = false;

    Object.entries(defaults).forEach(([key, value]) => {
      if (search.has(key)) return;

      needsReplace = true;
      search.set(key, value);
    });

    if (needsReplace) {
      navigate(`${location.pathname}?${search}`, { replace: true });
    }
  });

  return Object.fromEntries(search.entries());
}
```
And a component:
```tsx
export default function Foo() {
  const { bar } = useDefaultParams({ bar: 'baz' })
  return <div>Foo. bar={bar}</div>
}
```

### What I expect

Going to `/foo` redirects the user to `/foo?bar=baz`. The `Foo` component renders a total of two times, with the second time showing `Foo. bar=baz`.

Going to `/foo?bar=quux` renders `Foo. bar=quux.`

### What happens

Going to `/foo` redirects the user to `/foo?bar=baz`, but the `Foo` component and the `useDefaultParams` hook run infinitely.

Going to `/foo?bar=quux` renders `Foo. bar=quux.` (This is correct.)

**Comment by timdorr** [comment] 2022-08-21 01:03
Duplicate of #7634

**Closed** 2022-08-21 01:03 UTC
Labels: bug
