### ISSUE TITLE
[Feature]: Add theme toggle button for the docs please.

### ISSUE THREAD

**Issue by kei-ichi** [remix-run/react-router#8564] opened 2022-01-06 12:38 UTC
### What is the new or updated feature that you are suggesting?

Please add the theme toggle button for the main docs page please.
You force the page to match the system theme but the main page docs theme in black (yes, it match my macOS theme) are very very hard to read. So please, just add a small toggle them button.

### Why should this feature be included?

Because you give user no choice to switch between dark and light theme and the dark theme make it very very hard to read the docs. 

Edit: just to be clear, the white text contrast is just too high (especially the title text), you can easy compare your docs text contrast with GitHub dark them white text contrast.

**Comment by timdorr** [comment] 2022-01-06 16:25
Duplicate of #8437

**Closed by timdorr** 2022-01-06 16:25 UTC
Labels: feature
