### ISSUE TITLE
[Bug]: useLocation with MemoryRouter and location state seems broken in 6.4.0

### ISSUE THREAD

**Issue by icd2k3** [remix-run/react-router#9305] opened 2022-09-19 22:46 UTC
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

When using a `MemoryRouter` with `initialEntries` that include location state (like `[{ pathname: '/path', state: { isLocationTest: true } }]` the state does not get returned by `useLocation`... This works in `6.3.0`

#### 6.3.0 useLocation
```js
{
  pathname: '/path',
  search: '',
  hash: '',
  state: { isLocationTest: true },
  key: '4l3b4v4b'
}
```

#### 6.4.0 useLocation
```js
{
  pathname: '/path',
  search: '',
  hash: '',
  state: null,
  key: 'default'
}
```

### Expected Behavior

`useLocation` should return the expected location state within MemoryRouter

### Actual Behavior

`useLocation` returns `{ pathname: '/path', search: '', hash: '', state: null, key: 'default' }`

**Comment by icd2k3** [comment] 2022-09-19 22:47
I'm sorry, I think this is probably a dupe of https://github.com/remix-run/react-router/issues/9265

**Comment by timdorr** [comment] 2022-09-20 00:33
Duplicate of #9265

**Closed by timdorr** 2022-09-20 00:33 UTC
Labels: bug
