### ISSUE TITLE
[Bug]: path includes CJK characters can not be matched

### ISSUE THREAD

**Issue by yesmeck** [remix-run/react-router#9291] opened 2022-09-18 09:14 UTC
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

1. Visit https://stackblitz.com/edit/github-yjdjq8-upqh4l
2.  Click "你好"

### Expected Behavior

The page shows "你好"

### Actual Behavior

The page shows blank. After refreshing the page, it shows "你好" correctly.

**Comment by timdorr** [comment] 2022-09-19 14:57
Duplicate of #8577

**Closed by timdorr** 2022-09-19 14:57 UTC
Labels: bug
