### ISSUE TITLE
Does v6 support Umlauts? (ä,ö,ü,...)

### ISSUE THREAD

**Issue by mleister97** [remix-run/react-router#9044] opened 2022-07-09 18:38 UTC
### What version of React Router are you using?

6.3.0

### My Question/Bug Report

Is it true, that RRv6 doesn't support Umlauts in the URL like ä,ö,ü,... any more? The previous version, v5, did. We recently upgraded to v6 and are now experiencing that the new version doesn't match Routes including umlauts. Is there any way to allow these kind of special characters?

**Comment by timdorr** [comment] 2022-07-09 19:12
Duplicate of #8577

**Closed by timdorr** 2022-07-09 19:12 UTC
Labels: bug
