### ISSUE TITLE
[Bug]: history prop (createBrowserHistory object) is no longer supported for Router/BrowserRouter

### ISSUE THREAD

**Issue by curiousPerson777** [remix-run/react-router#8325] opened 2021-11-12 09:47 UTC
### What version of React Router are you using?

6.0.1

### Steps to Reproduce

App.tsx :

```
import { BrowserRouter } from "react-router-dom";

import  createBrowserHistory  from "history";

import MyRoutes  from ''./MyRoutes";

const history = createBrowserHistory(); // in v5 I could pass this const to <Router> component but in v6 its not possible with <BrowserRouter> nor with <Router>


// BrowserRouter (or any other router exported from react-router-dom) no longer accepts `history` prop like it did in version 5 so it won't be possible to redirect user using that history object in axios interceptor

function App() {
  return (
      <BrowserRouter>
          <MyRoutes />
       </BrowserRouter>
  );
}

export default App;


```

axios.ts:

```
import axios, { AxiosError } from "axios";
import { getToken, refreshAccessToken  } from "tokens";
import { API_URL } from "API";
import history from "history";


const AxiosSecured = axios.create({
  baseURL: API_URL,
});

AxiosSecured.interceptors.request.use((config) => {
  config.headers = {
    Authorization: `Bearer ${getToken()}`,
  };

  return config;
});

AxiosSecured.interceptors.response.use(
  (response) => response,
  async (err) => {
    const error = err as AxiosError;
    const originalConfig = error.config;

    if (error.response && error.response.status === 401) {
      try {
        await refreshAccessToken();

        return AxiosSecured(originalConfig);
      } catch (error) {
        // catch error when obtaining new access token failed

        history.push('/logout'); //  this won't work in react-router 6. You will get pushed to /logout but application won't display correct view for that url. Only url will change
      }
    }
    Promise.reject(err);
  }
);

export default AxiosSecured;

```

### Expected Behavior

I should be able to pass my own createBrowserHistory object in BrowserRouter or Router so I can use the same history object in axios interceptor and redirect users to any route if theirs refresh token expired (It was possible in react-router-dom v5)

### Actual Behavior

URL changes in browser but UI remains the same

**Comment by timdorr** [comment] 2021-11-12 12:21
Duplicate of #8264

**Closed by timdorr** 2021-11-12 12:21 UTC
Labels: bug
