### ISSUE TITLE
[Bug]: french characters don't seem to work in route paths

### ISSUE THREAD

**Issue by laem** [remix-run/react-router#8824] opened 2022-04-28 16:41 UTC
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Write a route with a `path` that has french accents in it, like "vie-privée" for instance.

Here is the basic example modified to show the bug : https://stackblitz.com/edit/github-5tq9g4?file=src%2FApp.tsx

### Expected Behavior

Accents in URL should work, the route should be matched.

### Actual Behavior

 The route is not matched.

**Comment by laem** [comment] 2022-04-28 16:50
Well, I've just found that it is a general issue https://github.com/remix-run/react-router/issues/8577#issuecomment-1012080691

> Paths with umlauts (äöüÄÖÜ) or the Scandinavian letter ø aren't working either. I suspect these issues are related.

This should be listed as a **major** limit to the v6.

**Comment by timdorr** [comment] 2022-04-29 02:17
I'm going to mark this as a duplicate of #8577

**Closed by timdorr** 2022-04-29 02:17 UTC
Labels: bug
