### ISSUE TITLE
<Link> does not understand external URL with protocol

### ISSUE THREAD

**Issue by davidtheclark** [remix-run/react-router#1147] opened 2015-04-30 23:15 UTC
If I use `<Link to='//google.com'>` it's fine; but if I use `<Link to='http://google.com'>` I get an error: `Uncaught Error: Invariant Violation: Cannot find a route named "http://google.com"`.

Based on the docs, I believe the `<Link>` component is supposed to handle full URLs as well as routes, so this appears to be a bug.

**Comment by taurose** [comment] 2015-05-03 14:19
I guess the docs are wrong. Instead of full URLs it should say full paths. For external links, just use `<a href>`.

**Comment by davidtheclark** [comment] 2015-05-03 15:17
If that's the case, then (with docs clarified) this issue still stands but as a feature request rather than a bug. (Also, it's confusing that the external links work without a protocol?)

Let's say I have an array of objects representing 20 links, a few of which are "routes" and a few of which are true URLs. I want to map those to components and render them. If `<Link>` doesn't understand how to deal with both, then I need to perform the logic myself that distinguishes between external URLs and routes and renders different elements accordingly.

Seems it would be nicer for react-router users if the provided `<Link>` did this for them. For the situation described above, I'd probably have to end up writing another component wrapping this logic and rendering either a `<Link>` or an `<a>` accordingly --- don't other react-router users want the same thing?

Or if other people know of a good existing way (or a better non-existing way) to take care of that use-case, I'd love to hear it. (e.g. page.js hijacks any `<a>` clicks and checks whether they apply to routes: https://github.com/visionmedia/page.js/blob/master/index.js#L539)

**Comment by ryanflorence** [comment] 2015-06-18 14:44
`<Link/>` is a router-aware anchor, if you want to link to an external site, use an `<a/>`.

**Comment by ryanflorence** [comment] 2015-06-18 14:46
Note, you could make your own Link that does the check and then renders an `<a/>` or a `<Link/>`

```js
var YourLink = React.createClass({
  render () {
    return this.isExternal() ? <a/> : <Link/>
  }
});
```

**Comment by geraldfullam** [comment] 2016-05-26 14:07
I agree with @davidtheclark . I just ran into this issue and began implementing my own component similar to the one you describe above to handle the logic, but it seemed so basic and obvious a concern and such common scenario that I stopped to check the react-router docs and issues for the "built-in" solution that I was certain existed. I am surprised that this feature is not built-in.

**Comment by shprink** [comment] 2016-06-15 07:36
I think everyone that uses React-Router end up writing a component like that. Good or Bad IDK but annoying indeed :P

**Comment by shprink** [comment] 2016-06-15 08:19
I created something like this if it helps

```
import React from 'react';
import {Link as ReactLink} from 'react-router';

export default class Link extends React.Component {
  parseTo(to) {
    let parser = document.createElement('a');
    parser.href = to;
    return parser;
  }
  isInternal(toLocation) {
    return window.location.host === toLocation.host;
  }

  render() {
    const {to, children, ...rest} = this.props;
    const toLocation = this.parseTo(to);
    const isInternal = this.isInternal(toLocation);
    if (isInternal) {
      return (<ReactLink to={toLocation.pathname} {...rest}>{children}</ReactLink>);
    } else {
      return (<a href={to} target="_blank" {...rest}>{children}</a>);
    }
  }
}
```

**Comment by robbyemmert** [comment] 2016-06-16 13:10
I agree with @shprink and @davidtheclark.  If you want to handle dynamic routes (which nearly every app does), you'll have to add this functionality.  Is there any reason that a URL with a protocol and a different domain should NOT be honored?  @ryanflorence, would you merge a PR if I added this functionality for you?

**Comment by taion** [comment] 2016-06-16 14:53
As currently set up this wouldn't be the correct place to put this logic – this ought instead to be handled by the history.

**Comment by joepsz** [comment] 2017-03-02 15:26
Thanks for the tip, @ryanflorence. I ended up writing this component to handle both:

```` javascript
import React, { Component, PropTypes } from 'react';
import { Link } from 'react-router';
import isExternal from 'is-url-external';

const propTypes = {
  to: PropTypes.string.isRequired,
};

/**
 * Link that also works for external URL's
 */
export default class LinkDuo extends Component {
  render() {
    return isExternal(this.props.to) ?
      <a
        href={this.props.to}
        {...this.props}
      />
      :
      <Link {...this.props} />;
  }
}

LinkDuo.propTypes = propTypes;
````

**Comment by saadaouad** [comment] 2017-08-22 18:24
Try to use this condition directly
```
{/^https?:\/\//.test(url)
? <a href={url} />
: <Link to={url} />
}
```

**Comment by joncursi** [comment] 2017-12-20 20:54
I wasn't able to use the `is-url-external` because my application needs to render server-side. Instead, I used the `validator` package to check if the `to` prop is an external URL or not:

```js
/* @flow */

import * as React from 'react';
import { Link as LinkImport } from 'react-router-dom';
import validator from 'validator';

type PropsFlowType = {
  to: string | Object,
};

const Link = ({
  to,
  ...otherProps
}: PropsFlowType): React.Node => (
  validator.isURL(to)
    ? (
      <a
        href={to}
        {...otherProps}
      />
    ) : (
      <LinkImport
        to={to}
        {...otherProps}
      />
    )
);

export default Link;
```

**Comment by mshwery** [comment] 2018-01-02 21:48
This should probably be covered in the `<Link />` component documentation. It is completely unexpected behavior right now.

The docs are misleading through omission – they say that a location object can be provided as the `to` prop, but do not mention that the protocol and origin properties within that location object are ignored, or that a full url string as the `to` prop will be applied relatively: `href="http://a.example.com/http://b.example.com"` instead of `href="http://b.example.com"`

**Comment by aluethi** [comment] 2018-01-14 13:57
Since I needed a TypeScript implementation with as few external dependencies as possible i made this drop in replacement of the Link class in react-router-dom. It might be of help to some of you as well:

`import * as React from 'react';
import { Link as RouterLink } from 'react-router-dom';

export default class Link extends React.Component<any, {}> {
    constructor(props: any) {
        super(props);
    }

    render(): JSX.Element {
        return /^https?:\/\//.test(this.props.to)
            ? <a href={this.props.to} {...this.props} />
            : <RouterLink {...this.props} />
    }
}`

**Comment by arttay** [comment] 2018-01-16 20:02
+1 for either adding this functionality or at min adding it to the docs. Spent a day trying to figure out why the app wouldn't link to external sources.

**Comment by franciscop-invast** [comment] 2018-02-05 02:22
My solution, including a no `to` option, an external link and an internal link:

```js
// What <Link> should always be
import React from 'react';
import { Link } from 'react-router-dom';

export default ({ to, children, ...props }) => {

  // It is a simple element with nothing to link to
  if (!to) return <span {...props}>{children}</span>;

  // It is intended to be an external link
  if (/^https?:\/\//.test(to)) return <a href={to} {...props}>{children}</a>;

  // Finally, it is an internal link
  return <Link to={to} {...props}>{children}</Link>;
};
```

Cannot remove that children (and let react use the `props.children` from `{...props}`) because [a11y complains](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-has-content.md) about the `<a>` not having a manual children even if they have from the `{...props}`.

**Comment by mattwills8** [comment] 2018-02-05 19:01
I created a render props component which you pass the url, a renderInternal function, and a renderExternal function as props.

It then checks if the link is internal or external, and calls either renderInternal or renderExternal. That way there's no messing around with trying to pass through any React-Router props, you can just pass your usual React-Router component to renderInternal

Looks a bit like this:

    class Prefix_Link extends Component {

      render () {

        // this is a function that for me either returned the url with host removed or returned false if it was an external url
        const internal = removeHostFromUrl(this.props.url) 

        return internal ? this.props.renderInternal(internal) : this.props.renderExternal(this.props.url)
      }
    }

     Prefix_Link.propTypes = {
        url: PropTypes.string.isRequired,
        renderInternal: PropTypes.func.isRequired,
        renderExternal: PropTypes.func.isRequired
    }

    export default Prefix_Link

**Comment by michalpleszczynski** [comment] 2018-04-16 14:19
Link renders 'a' element by default, but to apply its Link logic it checks (among other conditions) if target is not specified on the component. So for a minimal workaround you can do `<Link to={to} target="_self">` and it will act as a native 'a' element.

**Comment by mjackson** [comment] 2018-11-02 22:03
Let's re-open this until we can add some notes to the docs about using external links and add a warning for URLs with anything more than just a path in `<Link>`.

**Comment by mjackson** [comment] 2021-09-08 19:18
Actually, I'm thinking we just make `<Link>` work transparently for same-origin URLs and external ones. That way you don't have to remember when to use `<Link>` and when to use `<a>`, so the abstraction is a little more complete.

We should get this fixed in v5 and make sure it works in v6 too.

**Closed** 2021-12-10 20:39 UTC
Labels: feature
