### ISSUE TITLE
[Bug]: `matchPath` doesn't support optional parameters?

### ISSUE THREAD

**Issue by Shaddix** [remix-run/react-router#10594] opened 2023-06-13 05:02 UTC
### What version of React Router are you using?

6.12.1

### Steps to Reproduce

`const result = matchPath('/products/:id?', '/products/1')` returns `null` (expected not null).

Maybe it's not supported, but then Typescript types are confusing, because it correctly strips out the '?' symbol and says that `result.params` is `{ id: string | undefined }`.

### Expected Behavior

`const result = matchPath('/products/:id?', '/products/1')` returns non null value (with `result.params.id === '1'`)

### Actual Behavior

`matchPath('/products/:id?', '/products/1')` returns `null`

**Comment by timdorr** [comment] 2023-06-13 19:54
Duplicate of https://github.com/remix-run/react-router/issues/9793 / https://github.com/remix-run/react-router/discussions/9862

**Closed by timdorr** 2023-06-13 19:54 UTC
Labels: bug
