### ISSUE TITLE
[Bug]: NavLink active breaks when `to` contains trailing slash

### ISSUE THREAD

**Issue by njdancer** [remix-run/react-router#10506] opened 2023-05-19 03:49 UTC
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

Create a NavLink with `end` omitted or set to false and with `to` set to a route path which contains subroutes and ensure a trailing slash at the end.

Visit a subroute of the path in use.

### Expected Behavior

With `end` false, when the current location is a subroute of a mounted NavLink, then it should be active.

### Actual Behavior

NavLink is considered inactive.

This seems to be a result of the following line:

https://github.com/remix-run/react-router/blob/f397ad756530f879f5406726f830ff4edf2064e0/packages/react-router-dom/index.tsx#L576

Currently, when `end` false and the current location `startsWith(to)`, we are checking if the next unmatched character is a `/` to ensure the last segment wasn't only a partial match. This however is done assuming that `to` didn't already have a trailing slash which is not currently guaranteed to be the case. As such when it does contain a trailing slash it ends up comparing against the following character.

Unfortunately I could not create a repro via StackBlitz as the template was giving me an esbuild error at the time. Happy to provide this if StackBlitz starts working again.

**Comment by iamdey** [comment] 2023-07-20 14:32
We have the same issue with:

```jsx
<Navlink to="/">App</Navlink>
```
This link should be always active (since `end` is not true)

I've manage to reproduce and tried to describe expected behavior, cf. `Layout` component:

https://stackblitz.com/edit/github-1aweyn?file=src%2FApp.tsx

(Tell me if it's not clear enough).

**Comment by bilu7111** [comment] 2023-07-24 21:00
@ryanflorence I have fixed this issue for dev 
https://github.com/remix-run/react-router/pull/10734

**Comment by bilu7111** [comment] 2023-07-24 21:07
@brophdawg11

**Comment by bilalk711** [comment] 2023-07-26 20:16
@timdorr can you review my PR please?

**Comment by brophdawg11** [comment] 2023-10-31 20:11
This is resolved in via #10734 and will be available in the next release

**Closed by brophdawg11** 2023-10-31 20:11 UTC
Labels: bug
