### ISSUE TITLE
[Bug]: Navigate malfunction in createBrowserRouter

### ISSUE THREAD

**Issue by abhay187** [remix-run/react-router#10417] opened 2023-04-29 17:31 UTC
### What version of React Router are you using?

v6.11.0

### Steps to Reproduce

Check this repo https://stackblitz.com/edit/react-ts-ffc4fk?file=App.tsx

### Expected Behavior

When I go to `dashboard` route it should route to `/dashboard/profile`

### Actual Behavior

it is routing to `/dashboard/profile/profile`

**Comment by abhay187** [comment] 2023-04-29 17:32
The code was working as expected in v6.10.0

**Comment by huijiewei** [comment] 2023-04-30 08:50
same bug, only in the development env

**Comment by virendave96** [comment] 2023-05-01 06:46
My code earlier.

```
 <Routes>
  <Route index element={<Navigate to="db" />} />
  <Route path="db" element={<Db/>} />
  </Routes>
```

Working earlier but now I have to

  ```
<Routes>
    <Route index element={<Navigate to="/app/db" />} />
    <Route path="db" element={<Db/>} />
  </Routes>
```

**Comment by abhay187** [comment] 2023-05-01 10:40
@huijiewei Yes this issue is in dev env and upon inspection I realize it is occurring due to StrictMode.

**Comment by brophdawg11** [comment] 2023-05-01 20:16
Yeah this is definitely due to `StrictMode` firing effects twice and the inability to "cleanup" from a navigation.  It seems the reason this worked in 6.10 was the use of `useSyncExternalStore` inside React Router which flushed certain updates synchronously such that things were reflected in the second StrictMode effect.  

The usage of `useSyncExternalStore` caused some super nuanced react-state-syncing bugs so we've replaced it with `useState` in 6.11, and now the state is not flushed synchronously.  

I would argue that this is sort of "working as React expects" in that when you use `<Navigate>` you case a navigation side effect and there is no "cleanup" - so it happens twice.

The idiomatic way to do this with `RouterProvider` is to decouple navigation from rendering, and instead redirect from a `loader` instead of from the render cycle:

```jsx
{
  index: true,
  loader: () => redirect("profile"),
},
```

I'll dig in a bit deeper but I'm not sure if there's much we can do about this unfortunately since we don't have visibility into the pending async state in the second navigate 😕 .

**Comment by reintroducing** [comment] 2023-05-02 15:01
This is actually also breaking any call to Navigate in my app as well. This works fine in 6.10.0 but completely breaks in 6.11.0. The problem is compounded with a dynamic portion in the path. Take the following code:
```js
<Route
    path=":username"
    element={<Suspend child={<PatientContainer />} />}
    errorElement={<ErrorDisplayBoundary />}
>
    <Route index element={<Navigate to="overview" replace />} />
    <Route
        path="overview"
        element={<Suspend child={<Overview />} />}
        errorElement={<ErrorDisplayBoundary />}
    />
</Route>
```

In 6.10.0, if you landed on `patient/:username` (this is a nested route) you were redirected to `patient/:username/overview`, but in 6.11.0 this redirects to `patient/overview`, thus completely removing the dynamic username out of the URL and completely breaking the page (because the username is used in API loading for elements on that page). 

Same goes for anywhere else that I have a Navigate component.
```js
return createBrowserRouter([
    {
        path: '/',
        element: <Index />,
        errorElement: <ErrorDisplayBoundary />,
        children: [
            {
                index: true,
                element: <Navigate to="/reporting" replace />,
            },
            {
                path: 'census/*',
                element: <Navigate to="/members" replace />,
            },
```

These two routes redirected correctly, from `reporting` to `reporting/overview` (because the base of reporting redirects to reporting/overview) and same for `members` to `members/active` (since that is the redirect that should happen), but now they redirect to `overview` and  `active` respectively, which are not proper routes.

**Closed** 2023-05-02 20:56 UTC
Labels: bug

**Comment by reintroducing** [comment] 2023-05-03 15:32
@brophdawg11 i just tested `6.11.1-pre.0` and i can verify that it fixes all the issues I was seeing. thank you!
