### ISSUE TITLE
[Bug]: Route relative links not working as expected

### ISSUE THREAD

**Issue by RobinClowers** [remix-run/react-router#11067] opened 2023-11-28 18:24 UTC
### What version of React Router are you using?

16.20.0

### Steps to Reproduce

Route relative links that are nested under a splat route are not working as expected. Given a route like `<Route path="/regions/:slug/*" element={<Child />} />`, and a link on that route like `<Link to="bar">Subpage</Link>`, I would expect the first time I clicked the link to end up on `/regions/foo/bar`, and after than it wouldn't do anything, since I'm already at the `bar` relative path. This works currently in 16.18.0, but is broken in later versions.

I suspect https://github.com/remix-run/react-router/pull/10983 might have caused this issue, though it's not clear why.
 
I've created a reproduction: https://github.com/RobinClowers/react-router-relative-link-bug, you can view it on [StackBlitz](https://stackblitz.com/~/github.com/RobinClowers/react-router-relative-link-bug) if you prefer.

The main branch shows the issue, click "go to /regions/foo", then click "go to /regions/foo/bar" several times. Each time, `/bar` is appended to the url. If you checkout the branch "16.18.0", you will see clicking the second link doesn't cause that issue.

### Expected Behavior

My app is currently using 16.18.0, and clicking a route relative link that matches the current path does nothing.

### Actual Behavior

Clicking a route relative link that matches the current path appends the relative path.

**Comment by cduff** [comment] 2023-11-29 03:55
Duplicate or related to https://github.com/remix-run/react-router/issues/11052?

**Comment by brophdawg11** [comment] 2023-11-29 14:36
Yeah, this is a duplicate of https://github.com/remix-run/react-router/issues/11052 - let's track it over there

**Closed by brophdawg11** 2023-11-29 14:36 UTC
Labels: bug
