### ISSUE TITLE
[Bug]: When using unstable_useBlocker with initial value true, Works on the second transition.

### ISSUE THREAD

**Issue by g4yamanaka** [remix-run/react-router#10144] opened 2023-02-28 03:19 UTC
### What version of React Router are you using?

6.8.2

### Steps to Reproduce

1. Open https://stackblitz.com/edit/vitejs-vite-lja2ey?file=src/App.tsx
2. Click "1" link.
3. Click "home" link.
4. Click "home" once more.

### Expected Behavior

Confirm does pop up when first click.
The "2" link, which is set to true in the middle instead of the default, works as expected.

### Actual Behavior

Confirm does pop up when second click.

**Comment by jljouannic** [comment] 2023-03-13 10:15
Reproduced in version `6.9.0`.

There seems to be some kind of memory leak as the [`useEffect` cleanup](https://github.com/remix-run/react-router/blob/react-router%406.9.0/packages/react-router/lib/hooks.tsx#L879)  call in `useBlocker` function is never run for the first blocker instance (i.e. when `blockerKey === '1'`).

In fact we always fall in the condition where the ["A router only supports one blocker at a time"](https://github.com/remix-run/react-router/blob/react-router%406.9.0/packages/router/router.ts#L2273) warning message is displayed.

If you navigate from a route with a blocker and come back to it, the `blockerFunctions` size never cease to increase

**Comment by jljouannic** [comment] 2023-03-13 11:53
Here is a fork of the official "React Router Navigation Blocking Example" with _pnpm-patched_ dependencies for `react-router@3.9.0` and `@remix-run/router@1.4.0` packages, only "enhanced" with a few `console.log()`:

https://stackblitz.com/edit/github-v1v4kk?file=package.json

To illustrate the behaviour described above in my previous post:
- Open the forked ["React Router Navigation Blocking Example"](https://stackblitz.com/edit/github-v1v4kk?file=package.json),
- When app is loaded, open the console tab of your browser devtools,
- On the Navigation Blocking Example app on the right, click on the link "Three (Form with blocker)",
- Then click on "Four",
- Click again on "Three (Form with blocker)" and so on.

You will see in the devtools console that none of the "even" blockers is ever cleaned up

**Comment by francisco-sanchez-molina** [comment] 2023-03-13 16:08
Hello! I'm not exactly sure why it happens, but it's related to StrictMode, which causes a double load of useEffects, and here it's affecting the router context.

**Comment by francisco-sanchez-molina** [comment] 2023-03-13 16:18
Hello! I'm not exactly sure why it happens, but there's a part that's related to the StrictMode mode, which causes a double load of useEffect, and it's affecting the router context

**Comment by francisco-sanchez-molina** [comment] 2023-03-13 19:58
Yes! Sorry, I expressed myself poorly. In dev mode and strict mode, the double call is the expected behavior. But it seemed to me that there might be some relationship when looking at the console log of having strict mode active vs not having it:

- Strict mode on:
<img width="380" alt="image" src="https://user-images.githubusercontent.com/9049706/224817771-cf2b8d71-ef72-4715-8261-42800cd0c40d.png">
-Strict mode off:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/9049706/224817685-c520e4a0-f0dc-4af3-b915-b561adaef94e.png">

I actually arrived at this issue due to a blocking problem I have in dev but not in prod.

**Comment by jljouannic** [comment] 2023-03-17 16:22
Taken from [here](https://github.com/reactwg/react-18/discussions/19):
> when running in “strict mode“ React will [intentionally double-render components](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) for in order to flush out unsafe side effects.

In our case, isn't the auto-increment of `blockerId` each time `useBlocker` is called one of these so-called unsafe side effects?

**Comment by jljouannic** [comment] 2023-03-17 16:53
I have the feeling that the `blockerKey` state could simply be replaced by a call to the `useId` hook once the fix to the [following issue](https://github.com/facebook/react/pull/25713) will be released

**Comment by brophdawg11** [comment] 2023-06-09 14:21
This should be addressed by #10573 which will be available in the next release (`6.12.2` or `6.13.0`)

**Closed by brophdawg11** 2023-06-09 14:21 UTC
Labels: bug
