### ISSUE TITLE
[Bug]: Scroll Restoration not working on page refresh in mobile safari

### ISSUE THREAD

**Issue by fetters5** [remix-run/react-router#9463] opened 2022-10-14 13:35 UTC
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Scroll position is not maintained in mobile safari browsers  upon reload of a page. This is due to using  the beforeunload event which is not supported by ios safari 
```
function useBeforeUnload(callback: () => any): void {
  React.useEffect(() => {
    window.addEventListener("beforeunload", callback);
    return () => {
      window.removeEventListener("beforeunload", callback);
    };
  }, [callback]);
}
```

By changing the above code to use the visibilitychange event and checking  `document.visibilityState === 'hidden'` it seems to work as intended in safari

Reference material

https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event
https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/
https://levelup.gitconnected.com/how-to-send-an-asynchronous-request-at-the-end-of-a-page-session-90bf7229448c
https://tech.trivago.com/post/2020-11-17-exploringthepagevisibilityapifordetectin/

### Expected Behavior

Expect that when reloading a page the scroll position will be maintained in ios safari

### Actual Behavior

The scroll position goes to 0 since it  was not captured.

**Comment by jakkku** [comment] 2022-10-29 19:30
Here is the [codesandbox](https://codesandbox.io/s/react-router-dom-scrollrestoration-w3k9y7?file=/src/App.tsx)  
please check it on IOS mobile safari

**Comment by andrewalisa** [comment] 2023-01-25 04:18
Hi!

Using ScrollToTop on iOS Safari isn't working as intended. 

Will this this be fixed with the next version as well?

This doesn't happen on Android or any other web browser, only iOS Safari.

The code I'm using for ScrollToTop.js is: 

```js
import { useEffect } from "react";
import { useLocation } from "react-router-dom";

export default function ScrollToTop() {
  const { pathname } = useLocation();

  useEffect(() => {
    window.scrollTo({
      top: 0,
      left: 0,
      behavior: "smooth",
    });
  }, [pathname]);

  return null;
}
```

Placement of ScrollToTop:

```js
import React from "react";
import ReactDOM from "react-dom/client";
import "./index.css";
import App from "./App";
import reportWebVitals from "./reportWebVitals";
import { BrowserRouter as Router } from "react-router-dom";
import ScrollToTop from "./components/ScrollToTop";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
    <Router>
      <ScrollToTop />
      <App />
    </Router>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

```

Please let me know if  this is an issue that can be corrected on my end too.

**Closed** 2023-01-26 18:24 UTC
Labels: bug, awaiting release
