### ISSUE TITLE
React Router not working with imported class-based components after building

### ISSUE THREAD

**Issue by francojohnc** [remix-run/react-router#10595] opened 2023-06-13 13:34 UTC
### What version of React Router are you using?

6.12.1

### Steps to Reproduce

Create a new React project and include react-router-dom.
Create a functional component (e.g. ComponentA) that uses React Router for routing.
Create a class-based component (e.g. ComponentB).
Import ComponentB into ComponentA and include it in the routing.
Run the project in the local development environment (the routing works correctly in this case).
Build the project for production (npm run build).
Serve the production build (serve -s build).

### Expected Behavior

The router should route to ComponentB when its route is accessed, just like it does in the local development environment.

### Actual Behavior

After the production build, React Router does not route to the imported class-based component, and no errors are displayed in the console.

**Comment by brophdawg11** [comment] 2023-06-13 15:02
Duplicate of https://github.com/remix-run/react-router/issues/10579

**Closed by brophdawg11** 2023-06-13 15:02 UTC
Labels: bug
