### ISSUE TITLE
[Bug]: v6.12.1 Navigating and changing pages does not work. No errors in console

### ISSUE THREAD

**Issue by tipsxBase** [remix-run/react-router#10579] opened 2023-06-09 05:42 UTC
### What version of React Router are you using?

6.12.1

### Steps to Reproduce

![image](https://github.com/remix-run/react-router/assets/16009561/69547687-7938-408c-8bc1-3bb784f22187)

I am encountering an issue in my React 18 environment where the setStateImpl method is not being called. I have thoroughly reviewed my code and ensured that I am using React version 18. However, despite my expectations, the setStateImpl method does not seem to be invoked.

### Expected Behavior

I expect the setStateImpl method to be called and perform the state update as intended.

### Actual Behavior

I am facing an issue after upgrading my environment to React 18 and react-router-dom v6.12.1. Initially, my pages were rendered correctly when I was using react-router-dom v6.10.0. However, after upgrading to v6.12.1, I encountered a white screen issue. Upon debugging the code in the browser console, I noticed that the setStateImpl method is not being called at the specific location within the RouterProvider component in react-router/lib/component.ts, which is causing the white screen to appear.

![image](https://github.com/remix-run/react-router/assets/16009561/69547687-7938-408c-8bc1-3bb784f22187)

**Comment by krisgerhard** [comment] 2023-06-09 06:26
+1 with React 18

`6.11.2`
Everything works as expected
`6.12.0`
Navigating and changing pages works.
Had an issue with changing route inside the same React Component. For example `/page` -> `/page/1`
componentDidUpdate did not receive the parameter `1`. Thought it's an issue with my implementation and did not dig deeper.
`6.12.1`
Navigating and changing pages does not work. Brower URI changes but pages are not loaded. No errors in console.

**Comment by BlackEyeByLee** [comment] 2023-06-09 06:52
+1 with React 18

**Comment by ns4style** [comment] 2023-06-09 07:04
got same behavior after updating to 6.12.1. 
webpack dev bundle is ok but navigation of production bundle doesn't work.
After small investigation I got that any minimazer plugin is causing this strange behavior. (I tried Terser and Esbuild minimazer).

**Comment by aerialist7** [comment] 2023-06-09 07:28
+1
React 18.2.0

**Comment by birdofpreyru** [comment] 2023-06-09 11:03
Same problem &mdash; in my existing project everything worked fine with `react-router-dom@6.12.0`; after an upgrade to v6.12.1 the navigation via `Link` elements broke in a peculiar way:
- No links work in my project's production build, no errors in console / no errors captured by a remote error tracking system (Sentry);
- Links still work fine in development build, running locally.
- Links still work both in production and development build of my simple test project. The difference between it, and my real project &mdash; the test one barely uses a few Suspenses for code splitting, and links still work across them; the real project heavily relies on suspenses to code-split different parts of the app, and thus I guess the way 6.12.0 messed up with the transitions did not account for complex projects with many nested suspenses, and to be safe it is probably better to downgrade to v6.11.2 until the root cause of the issue is fixed in `react-router-dom`.

**Comment by gillsoftab** [comment] 2023-06-09 11:07
Please test your code before deploying to production.

**Comment by Razviar** [comment] 2023-06-09 11:19
Yeah, same here, in prod "react": "18.2.0", after upgrade to "react-router-dom": "6.12.1" all navigation got broken: router just ignores any navigate actions, but URI in browser changes. Downgrade to 6.11.2 fixes the issue.

For dev enviroment everything is working weirdly.

**Comment by muresanandrei** [comment] 2023-06-09 13:25
Same here holy it seems something has been broken

**Comment by brophdawg11** [comment] 2023-06-09 15:15
Looking into the reproduction in https://github.com/remix-run/react-router/issues/10579#issuecomment-1584065651, I believe the root cause in that example seems to be calling `React.lazy` _inside_ the render cycle, which results in a new `Promise` being created on each render.  Internally React deals with thrown promises by [adding custom fields](https://github.com/acdlite/rfcs/blob/first-class-promises/text/0000-first-class-support-for-promises.md#reading-the-result-of-a-promise-that-was-read-previously) but if it's a net-new promise each time it will never see those custom fields and get's itself into an infinite Suspense loop.

Lifting those `React.lazy` calls out of the render cycle fixes the issue: https://codesandbox.io/s/dawn-rgb-yzvtcw?file=/src/App.js.  Note I also changed `LazyLoad(Comp)` to `<LazyLoad Comp={...} />` since I don't think you're technically supposed to be calling React components and normal functions.

Does anyone else have an alternate reproduction we could look into to see if there is a core issue with how we're using `startTransition` or if this is just a nuance about how React 18 handles concurrent rendering?  

In some cases, we think that built-in React behavior might be the source of confusion in that with transitions they don't re-show already resolved Suspense boundaries, so in some cases you can also add a `key` to your Suspense boundary if it's not re-showing.  See https://github.com/remix-run/react-router/issues/10568.

**Comment by birdofpreyru** [comment] 2023-06-09 15:39
@brophdawg11 While the new React docs say indeed that `lazy()` should not be used inside the render function of another component (https://react.dev/reference/react/lazy#my-lazy-components-state-gets-reset-unexpectedly) (though, still don't forbid it completely); the legacy docs (which were the official docs until very recently) never told so: https://legacy.reactjs.org/docs/code-splitting.html#reactlazy . Thus, I guess, lots of people use it the way which is incompatible with changes you did in `react-router-dom`. IMHO, ideally, you should try to correct your changes to ensure they don't break stuff when `lazy()` is used inside another component; alternatively, you probably can detect it somehow and throw a hard error in such case (so it always breaks in both prod and dev, and not like now &mdash; only in prod, and not in every codebase)?

**Comment by brophdawg11** [comment] 2023-06-09 15:48
> lots of people use it the way which is incompatible with changes

I agree - this is why I'm asking for more reproductions.  That will give is a more complete picture of the ways folks in which are using Suspense features today that don't play nice with `startTransition` and make sure we come up with the right solution.

Is calling `lazy` inside render the same root issue in your application?  If not, would you be able to provide a reproduction of your scenario?

**Comment by Doridian** [comment] 2023-06-09 19:16
In the same boat here, 6.12.0 works, 6.12.1 breaks.
I am using `lazy` in the project, but not inside the render. (Full code is here, but I don't expect anyone to actually dig through this, I'll try and cut it down to a minimal repro: https://github.com/foxCaves/site/blob/chore/update-router/frontend/src/app.tsx#L19 )

**Comment by Doridian** [comment] 2023-06-09 19:29
> > In the same boat here, 6.12.0 works, 6.12.1 breaks.
> 
> Huh, any chance that's a typo and supposed to say `6.11.0` works? If `6.12.0 -> 6.12.1` is breaking for you a reproduction would be awesome. The only change in `6.12.1` was to avoid a compilation issue for `webpack`/`react@17` - but both of them should be wrapping your router updates in `React.startTransition`...

Funnily enough, no. I've spent 2 hours yesterday trying to comprehend how a change from a string to a constant would have the ability to break anything.
But, for a matter of fact, this PR here: https://github.com/foxCaves/site/pull/446/files fails the E2E browsertests, while the state before it passes. (And manual testing shows `.1` and only `.1` breaks navigation).

Sites load, the initial page you loud routes correctly, but clicking any link just changes the address bar and doesn't load the actual page/content.

**Comment by jlowcs** [comment] 2023-06-09 19:30
Nope, I can confirm that 6.12.1 is the issue on my end as well. 6.12.0 works fine.

I can help investigate but not before Tuesday sadly.

**Comment by brophdawg11** [comment] 2023-06-09 20:08
That is ... surprising that the `6.12.0 -> 6.12.1` fix could change any behavior 😂.  If anyone is able to provide a simplified reproduction of that it would be super helpful, I'll see if I can reproduce it in the meantime.

While we dig into the underlying React behavior a bit here, if you're running into this, it's best to stay on 6.11 for a bit longer.

So far it seems like this is a bit of a case of the fact that Suspense has been "released" for some time but not fully understood (by us included!) so we're sort of "holding it wrong" in some cases.  Now that Suspense is a bit better documented/supported/understood, we're seeing `startTransition` expose some of those issues.

If you want to try to get your current app working in the interim (and better prepare your code for a fully-concurrent/transition-enabled world):
* Avoid re-creating net new promises on renders.  Either by lifting them out of the component (i.e., call `React.lazy()` at the top of your module) or by wrapping the promise creation in `useMemo`.  Either of those should fix the issue since React will be able to re-use the same promise on the subsequent concurrent render.
* If you can't get around the new Promise creation, you can add a `key` to your Suspense boundary to trigger a new instance which will be allowed to fall back in concurrent mode.

We'll keep digging into these reproductions and figure out the best path forward.  Sorry for the hiccup!

**Comment by hongz1** [comment] 2023-06-09 20:21
I haven't updated react-router-dom since v6.8.2 and it suddenly had this problem.
I upgraded to v6.12.0 and it worked fine.

**Comment by brophdawg11** [comment] 2023-06-09 20:32
@Doridian Are there any specific links that fail for you?  I cloned your site and ran the `/frontend` app in both dev and prod (with a stubbed `window.FOXCAVES_CONFIG`) mode and didn't have any issues routing between the homepage and `/login` and `/register`

**Comment by simPod** [comment] 2023-06-09 20:38
For me the issue is on the same route with changed parameters.

E.g., /article/1 vs /article/2

**Comment by gillsoftab** [comment] 2023-06-09 20:42
I don't know how your pipline setup looks like, but it might be a good idea to add smoke tests (i.e. puppeteer, selenium etc) in a real browser to catch issues like this before it enters production / becomes public. Then it will fail in the pipline for dev / staging. When will you do a rollback and redo it properly since 6.12.x did break the current implementation for many companies?

**Comment by Doridian** [comment] 2023-06-09 20:45
@brophdawg11 Dev mode navigation works. For me navigation only breaks (but reliably so) in a production build. 
You have to `NODE_ENV=production npm run build`. Only then is it broken. (You either have to symlink `/static` to the build folder or change https://github.com/foxCaves/site/blob/main/frontend/webpack.config.ts#L23 to always be `/`

**Comment by Doridian** [comment] 2023-06-09 21:33
Interestingly, this only happens with code minifcation enabled. I wonder if this hit a bug in the minifier webpack uses?

**Comment by Doridian** [comment] 2023-06-09 21:44
Looking at the minified code portion of the `startTransition` thing:
```js
[...]
const _ = 'startTransition';
function w(e) {
    let { basename: t, children: s, window: l } = e,
        u = o.useRef();
    null == u.current && (u.current = (0, i.lX)({ window: l, v5Compat: !0 }));
    let c = u.current,
        [d, f] = o.useState({ action: c.action, location: c.location }),
        p = o.useCallback(
            (e) => {
                _ in (r || (r = n.t(o, 2))) || f(e);
            },
[...]
```
It is quite hard to read anything in the minified stuff, but it almost seems as if it misinterprets the `x in y ? A : B` and gets the order of things wrong? (Judging from the `||` being inside the thing the `in` checks)
I'll try playing around with this and see how various things minify...

**Comment by brophdawg11** [comment] 2023-06-09 22:08
Yeah that's exactly where I'm at.  It's definitely getting minified into an incorrect flow where `startTransition` never actually gets called on the path where it is found in `React`.  I'll need to see if I can find a small reproduction in `terser`, or we'll need to find another solution for the webpack+react@17 compilation issue fixed in #10569

**Comment by msveshnikov** [comment] 2023-06-10 08:42
Just broke my production because of this bug :( Good that revert took just 30 minutes

**Comment by azangru** [comment] 2023-06-10 13:36
> Interestingly, this only happens with code minifcation enabled. 

Plus one to this. `6.12.1` works for me in dev build, but breaks in production build.

**Comment by Harmelodic** [comment] 2023-06-11 16:57
Also faced this issue.

- Renovate bot bumped application to `6.12.1`.
  - Commit: https://github.com/Harmelodic/website/commit/ee9d4c4d801379723b8a66c082ce335cd90686e2
  - Navigation is broken in production build.
  - Navigation is functional in development/local build.
- I changed to `6.11.2`.
  - Commit: https://github.com/Harmelodic/website/commit/9ab4c1503037b16ad608dc9de51af123c26847ba
  - Navigation is functional in both production & development.
- I changed to `6.12.0`.
  - Commit: https://github.com/Harmelodic/website/commit/6c3bb789484e8d7a7f10c7aeb00c7c4b42d6d283
  - Navigation is functional in both production & development.

All code found here: https://github.com/Harmelodic/website  
Live site found here: https://harmelodic.com  

Feel free to clone and play around as part of troubleshooting.

**Comment by gillsoftab** [comment] 2023-06-11 17:50
I solved it by creating extracting used functions to a file, mainly for navigation and routing. Now I don't need to import react-router and react-router-dom at all. It doesn't work for us to have such important functionality to break now and then.

[Custom react-router-dom](https://github.com/gillsoftab/react-navigation/blob/main/react-router-dom.js) **Can be used if you only use:**
BrowserRouter, HashRouter, HistoryRouter, Navigate, Route, Routes, useNavigate, useParams

Other files in that repo shows simple example how it can be used, it will cover 99,9 % of your needs. However, If you use it you should write proper tests and look for CVE issues at a regular interval / in your pipeline.

**Comment by fkrauthan** [comment] 2023-06-11 17:58
I can also confirm: After upgrading to react-router-dom 6.12.1 it failed on prod build (using webpack) with URL changing but the actual page never changed. Just downgraded to 6.12.0 and everything started working again (everything else being unchanged).

**Comment by msveshnikov** [comment] 2023-06-12 07:12
Why not withdraw version 6.12.1 until that critical bug is fixed? Otherwise tons of people will come here and will complain (I agree that everyone should have thier own QA process, but this particular bug is really nasty). Don't you have any QA process in react-router-dom?

**Comment by nareshONB** [comment] 2023-06-12 07:12
please release a break-fix soon. We have auto upgrades using dependabot in our production env, and this breaks our production. Temporarily ignored upgrades of react-router-dom till a new patch is released.

for anyone who is facing the same

```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "react-router-dom"

```

**Comment by JaywardhanCharan11** [comment] 2023-06-12 08:16
I am still facing this issue, upgraded to 6.12.0 . 
We are facing problem in production build. Please can someone direct me in a direction to resolve this issue.

**Comment by Naveenms1997** [comment] 2023-06-12 12:23
We are also facing same issue, then we downgraded react-router-dom version to 6.11.2. its working fine now

**Comment by kuzmenko-oi** [comment] 2023-06-12 13:24
Just pitching in to draw more attention to it - having the same issue. If I log every time useLocation changes, it logs the same navigation over and over
![image](https://github.com/remix-run/react-router/assets/102225324/aad08ab0-92a0-45dd-9699-957e00f9e151)

**Comment by rnkdsh** [comment] 2023-06-12 14:41
+1 with React 18

**Comment by ShubhamKKedia** [comment] 2023-06-12 15:59
i was using v6.9.0 and suddenly started to have this problem. I tried v6.12.0 v6.12.1 but it didn't solved the issue. Can someone help

**Comment by gillsoftab** [comment] 2023-06-12 16:01
> i was using v6.9.0 and suddenly started to have this problem. I tried v6.12.0 v6.12.1 but it didn't solved the issue. Can someone help

Please read the comments... downgrade to 6.11.2 and it will work.

**Comment by hongz1** [comment] 2023-06-12 16:10
> i was using v6.9.0 and suddenly started to have this problem. I tried v6.12.0 v6.12.1 but it didn't solved the issue. Can someone help

I had same issue (my version was 6.8.2) and 6.12.0 worked fine. try 6.11.2

**Comment by ShubhamKKedia** [comment] 2023-06-12 16:21
I tried v6.11.2 but it didn't work unfortunately

**Comment by dobladov** [comment] 2023-06-12 16:23
> I tried v6.11.2 but it didn't work unfortunately

@ShubhamKKedia are you using the exact version without the symbol `^` as this?
```json
    "react-router": "6.11.2",
```

**Comment by birdofpreyru** [comment] 2023-06-12 16:23
> _I tried v6.11.2 but it didn't work unfortunately_

Yeah? And when you do `npm ls react-router-dom` does it say you are using 6.11.2 indeed?

**Comment by brophdawg11** [comment] 2023-06-12 16:26
Hey folks - it looks like throughout this thread there are two separate issues being discussed:

**1. `6.12.1`-only Production Mode Issue**

`6.12.0` works correctly, but `6.12.1` doesn't perform navigations in production mode (works correctly in dev mode).  This is due to a `webpack`/`terser` minification issue introduced in #10569 and resolved by #10588 and currently available in `6.12.2-pre.0`.  If this is what your are seeing in your application, please give `6.12.2-pre.0` a shot and add a 👍 reaction to this comment to let us know that the prerelease resolves your issue.  If you still have issues with the prerelease, please respond with a comment and ideally a minimal reproduction.

**2. `startTransition`-enabled Navigation Issues**

`6.12.0` and `6.12.1` don't work correctly in your app when your navigations leverage `Suspense` internally, likely due to the recreation of net-new promises during renders.  This is shown by the codesandbox in [this comment](https://github.com/remix-run/react-router/issues/10579#issuecomment-1584065651) and further [here](https://github.com/remix-run/react-router/issues/10579#issuecomment-1584749371) and the few comments following.  If this is your issue we're still diving into this and hope to have an update for you shortly.

Apologies for the inconvenience and thanks for bearing with us!

**Comment by ShubhamKKedia** [comment] 2023-06-12 16:37
> > I tried v6.11.2 but it didn't work unfortunately
> 
> @ShubhamKKedia are you using the exact version without the symbol `^` as this?
> 
> ```json
>     "react-router": "6.11.2",
> ```

no

**Comment by valmirw** [comment] 2023-06-12 20:08
+1
react - ^18.2.0
react-router-dom: ^6.3.0

**Comment by carbonatedcoder** [comment] 2023-06-12 21:54
Just echo'ing the above. We started seeing the issue in production with 6.12.1. It breaks navigation completely. A white screen is encountered, no errors in the console. The single route will load upon refresh, but navigation between routes doesn't work. Running the project in dev mode works fine.

We make use of `React.lazy` to code split a few things. When removing the lazy loading, navigation works on 6.12.1. Downgrading to 6.12.0 works with the lazy loading included.

**Comment by justrealmilk** [comment] 2023-06-13 02:19
Also using lazy imports to break up my bundles. 6.12.0 doesn't work, had to return to 6.11.2.

**Comment by ldwonday** [comment] 2023-06-13 02:24
+1，v6.12.1 not work in production,but worked in v6.11.2

**Comment by ShubhamKKedia** [comment] 2023-06-13 04:39
using exact version v6.11.2 works.

**Comment by ElizaTok** [comment] 2023-06-13 07:25
> I tried v6.11.2 but it didn't work unfortunately

Please make sure your `package.json` was changed as well. Not only the `react-router-dom` version but also sub-dependencies like `@remix-run/router`, `react-router`. It is not happening automatically when downgrading for some reason.

**Comment by namezis** [comment] 2023-06-13 08:29
I used 6.12.2-pre.0 today with success.

The lazy loading works. I cannot wait for the formal release...

**Comment by remarkablemark** [comment] 2023-06-14 02:22
Would it be possible going forward to release a revert patch when a bug is confirmed so that repositories with Dependabot enabled wouldn't accidentally merge the bug?

**Comment by RajanKumarGoyal** [comment] 2023-06-14 03:42
I am also facing the same Problem yesterday, Earlier it was working good. Yesterday I Found out that my routes are not working properly in production mode but its working good in development mode. It was a strange behaviour.

After reading the above thread & spent couple of hours on this, I concluded that you can resolve this "route change but not rendering view" issue from 2 ways.

- Either remove the lazy loading from your main component (Then routes will render both for 6.12.1 and 6.12.0 as well in Production mode as well) 
- Or Upgrade your react-router-dom package to "6.13.0-pre.1". This will resolve your issue with lazy loading. And wait for "6.13.0" stable version.

Thanks!

**Comment by dobladov** [comment] 2023-06-14 08:02
`6.13.0-pre.1` solves the navigations issues for me, while using **Suspense** and **lazy** loading.

**Comment by ricardasjak** [comment] 2023-06-14 12:43
`"react-router-dom": "^6.3.0"` broke it out of nowhere, never ever use default npm version tagging, when minor version can be updated by vendor anytime.

quick fix is to freeze the version:
`"react-router-dom": "6.3.0"`

**Closed** 2023-06-14 15:58 UTC
Labels: bug

**Comment by brophdawg11** [comment] 2023-06-14 16:10
Hey folks, this should now be resolved in [`6.13.0`](https://github.com/remix-run/react-router/releases/tag/react-router%406.13.0).  Thanks again for bearing with us and helping us triage the issue and apologies for any inconvenience!

As a reminder we would recommend you pin your dependencies in `package.json` so version bumps are appropriately validated/tested.  In an ideal world every patch and minor bump would go smoothly, but with such a large landscape of libraries and bundling approaches it's tough to ensure that nothing ever slips though.

**Comment by bluepeter** [comment] 2023-06-14 18:53
Release 6.12.1 didn't work for many folks (as this issue demonstrates). Release 6.13.0 fixes things, but the release notes for that state:

> The tl;dr; is that 6.13.0 is the same as [6.12.0](https://github.com/remix-run/react-router/releases/tag/react-router%406.12.0) bue we've moved the usage of React.startTransition behind an opt-in future.v7_startTransition [future flag](https://reactrouter.com/en/main/guides/api-development-strategy) because **we found that there are applications in the wild that are currently using Suspense in ways that are incompatible with React.startTransition**.

Can someone provide guidance on the "incompatible" ways some of us may be using `Suspense`, `lazy`, etc? Right now, we are using the approach pretty much the same as that in https://github.com/remix-run/react-router/blob/dev/examples/lazy-loading/src/App.tsx

It would be good to get some guidance on how we can remedy our code to use `startTransition`...

**Comment by brophdawg11** [comment] 2023-06-14 20:21
Keep reading further in the release notes 😉 

>  Issues usually boil down to creating net-new promises during the render cycle, so if you run into issues when opting into `React.startTransition`, you should either lift your promise creation out of the render cycle or put it behind a `useMemo`.

Notice how in the example you link to in the repo, `React.lazy()` is called at the top-level module scope, thus creating the Promise outside of the render cycle (✅).  Compared to the reproduction higher in [this issue](https://github.com/remix-run/react-router/issues/10579#issuecomment-1584749371) which is calling `React.lazy` inside the render cycle, and thus creating a new promise each time (❌).

Another thing to keep in mind is the `Suspense` behavior to not fallback again after resolving, from the same [comment](https://github.com/remix-run/react-router/issues/10579#issuecomment-1584749371) above:

> In some cases, we think that built-in React behavior might be the source of confusion in that with transitions they don't re-show already resolved Suspense boundaries, so in some cases you can also add a key to your Suspense boundary if it's not re-showing. See https://github.com/remix-run/react-router/issues/10568.

**Comment by bluepeter** [comment] 2023-06-14 20:35
Thank you very much for the detailed reply @brophdawg11

**Comment by sethlivingston** [comment] 2023-07-10 21:20
I'm seeing this in 6.14.1, but not in 6.13.0.

**Comment by brophdawg11** [comment] 2023-07-11 14:40
@sethlivingston would you mind opening a new issue with reproduction steps?

**Comment by siosio34** [comment] 2023-08-28 11:13
This issue is still reproduced in version 6.15.0.
We are using lazy and suspense and the code below doesn't work.

```tsx

export default function Redirect({ to }: RedirectProps): JSX.Element {
  const params = useParams()

  const { search } = useLocation()

  const navigate = useNavigate()

  useEffect(() => {
    navigate(
      {
        pathname: generatePath(to, params),
        search,
      },
      { replace: true }
    )
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return null
}
```

**Comment by brophdawg11** [comment] 2023-08-28 16:22
@siosio34 would you mind opening a new issue with a minimal reproduction?

**Comment by conqr2** [comment] 2023-08-30 03:11
We've reproduced this in version `6.11.2`. We're using Create-React-App with a BrowserRouter and doing the below raises no logs or errors and has no effect.

```tsx
function Hook (){
   const navigate = useNavigate();
   
   const longTask = async () => {
      // await 5 second long task
      navigate("/link"); // does nothing
   };
   
   return <button onClick={longTask}>Task</button>;
}```

**Comment by brophdawg11** [comment] 2023-08-30 14:41
Come on folks, I really don't know how to say this any clearer.  Please do not comment on this closed issue with new problems.  Please open a new issue with a reproduction in codesandbox, stackblitz, or a github repo.  You can link to this issue from the new issue if you think it's a regression of the same type of issue.

**Comment by KrzysztofZawisla** [comment] 2023-11-18 22:10
I know that there is a request to don't reply in this thread, but for everyone like me who struggle with these errors, and don't see any solution on the internet, try to test your code without StrictMode.
