### ISSUE TITLE
[Bug]: Matching in the middle of URL's

### ISSUE THREAD

**Issue by Eth-a-n** [remix-run/react-router#9089] opened 2022-07-22 15:14 UTC
### What version of React Router are you using?

v6

### Steps to Reproduce

In V5 the use of regex was super useful for my teams use-case as we have SEO created URL's and we only know which path to visit via a common part of the url, often in the middle of the URL, so for example we would have something like this ...

`/this/url/is/created/by/an/seo/manager/{common path identifier}/more/seo?somequery` for this we would do something like `*/{ common path identifier}/*` as the path matcher

`/this/url/is/created/by/an/seo/manager/{different common path identifier}/more/seo?somequery` for this we would do something like `*/{different common path identifier}/*` as the path matcher

`/this/url/is/created/by/an/seo/manager/{other more different common path identifier}/more/seo?somequery` for this we would do something like `*/{other more different common path identifier}/*` as the path matcher

This is compounded for us having to support many different languages, so the URL's get localised (the common path identifier would stay the same in these cases though)

### Expected Behavior

I can't see a way this could be done in V6, is there a clear way to use v6 for this use case.

### Actual Behavior

Not currently possible to upgrade to V6 as this is a hard blocker for my team

**Comment by timdorr** [comment] 2022-07-24 01:32
Duplicate of #8254

**Closed by timdorr** 2022-07-24 01:32 UTC
Labels: bug
