### ISSUE TITLE
[Feature]: Requirement to check the length of the history stack in v6.

### ISSUE THREAD

**Issue by yati-malik** [remix-run/react-router#9270] opened 2022-09-15 13:56 UTC
### What is the new or updated feature that you are suggesting?

Length of history stack.React router v5 has the feature to check the length of the history stack. But this feature is missing in react router v6. 

### Why should this feature be included?

We are using it to check if there is nothing to go back in the history, if that is the case then we direct the user to some other page.

**Comment by timdorr** [comment] 2022-09-15 14:22
Duplicate of #9159

**Closed by timdorr** 2022-09-15 14:22 UTC
Labels: feature
