### ISSUE TITLE
[Bug]: Regression of `useResolvedPath` in 6.19.0 and `<Link to>` in 6.20.0

### ISSUE THREAD

**Issue by slax57** [remix-run/react-router#11053] opened 2023-11-23 10:49 UTC
### What version of React Router are you using?

6.20.0

### Steps to Reproduce

Consider the 3 following sandboxes.

The code is exactly the same, only the react-router-dom version is changed:

- https://stackblitz.com/edit/github-xg73s9-6ij7sr?file=package.json,src%2FApp.tsx : version 6.18.0
- https://stackblitz.com/edit/github-xg73s9-cjahhy?file=package.json,src%2FApp.tsx : version 6.19.0
- https://stackblitz.com/edit/github-xg73s9-sa2bgx?file=package.json,src%2FApp.tsx : version 6.20.0

Steps to reproduce (in each sandbox):
- Click on 'Tabs'
- Click on 'Tab 1'
- Click on 'Tab 2'
- Click on 'Tab 3'

### Expected Behavior

The expected behavior is the one exhibited by version 6.18.0:
- The current location pathname is `"/tabs/3"`
- The active tab is Tab 3 (the text "Tab 3 content" is visible)

### Actual Behavior

In version 6.19.0:
- The current location pathname is correct `"/tabs/3"` ✅️
- However the active tab is Tab 1 instead of Tab 3 (the text "Tab 1 content" is visible) ❌️

In version 6.20.0:
- The current location pathname is wrong: `"/tabs/2/3"` instead of `"/tabs/3"` ❌️
- The active tab is also wrong: Tab 1 instead of Tab 3 (the text "Tab 1 content" is visible) ❌️

Additional info:
We noticed that there has been some changes in [6.19.0](https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v6190) and [6.20.0](https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v6200) regarding the way splat routes are handled, but to my eyes, none of them explain this change in behaviour.

Can you please help us figure out if this is indeed a regression, or if we are doing something wrong in the way we implemented our tabs system?

Thanks.

**Comment by KubaOczko** [comment] 2023-11-23 14:38
We have encountered the same issue. The `useResolvedPath('')` (the empty string parameter is the important part) is used for the current context path location, and it behaves differently since version 6.18.0.

**Comment by chinfeng** [comment] 2023-11-23 16:02
same as #11052

**Comment by timdorr** [comment] 2023-11-24 17:04
Duplicate of #11052

**Closed by timdorr** 2023-11-24 17:04 UTC
Labels: bug
