### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by mr-new-0509** [remix-run/react-router#8103] opened 2021-10-04 01:47 UTC
### What is the new or updated feature that you are suggesting?

Hello.
Can't I use useHistory hook in the version6?

### Why should this feature be included?

As you know useHistory is useful hook.
Since version 5 I can use this hook but I can't import it from 'react-router-dom' in the version 6.
How can I fix this?

**Comment by timdorr** [comment] 2021-10-04 14:35
Duplicate of #7476

**Closed by timdorr** 2021-10-04 14:35 UTC

**Comment by mr-new-0509** [comment] 2021-10-05 08:02
Thanks.
