### ISSUE TITLE
[Bug]: util matchRoute doesn't work with optional segments

### ISSUE THREAD

**Issue by mchalik** [remix-run/react-router#10070] opened 2023-02-08 13:09 UTC
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

If you try to use matchPath with a pattern that contains optional segments, the result will be null.

### Expected Behavior

`matchPath('/some/:param?', '/some/test-param') // result will be null

### Actual Behavior

`matchPath('/some/:param?', '/some/test-param') // result should be founded pattern

**Comment by timdorr** [comment] 2023-02-08 16:41
Duplicate of #9793 / #9862

**Closed by timdorr** 2023-02-08 16:41 UTC
Labels: bug
