### ISSUE TITLE
[Bug]: v7pre - Await types are not implemented

### ISSUE THREAD

**Issue by shmuli9** [remix-run/react-router#12082] opened 2024-10-06 13:25 UTC
### What version of React Router are you using?

7.0.0-pre.0

### Steps to Reproduce

Use Suspense with Await to render a promised item
The type on the resolved item are fixed as `any`

```jsx
import { Suspense } from "react";
import type * as Route from "./+types.page";
import { Await } from "react-router";

export async function loader() {
    const promise = new Promise<{
        userId: number;
        id: number;
        title: string;
        completed: boolean;
    }>((resolve) => {
        resolve({
            ...
        });
    });

    return {
        data: promise,
    };
}

export default function Page({ loaderData, params }: Route.ComponentProps) {
    const { data } = loaderData;
    return (
        <div>
            <div>
                <Suspense fallback={<div>Loading...</div>}>
                    <Await
                        resolve={data} /* <-- typed correctly as Promise<{
                                                                        userId: number;
                                                                        id: number;
                                                                        title: string;
                                                                        completed: boolean;
                                                                      }> 
                                        */
                        children={(res /* <-- typed incorrectly as any */) => (
                            <div>
                                ...
                            </div>
                        )}
                    ></Await>
                </Suspense>
            </div>
        </div>
    );
}

```

### Expected Behavior

The resolved type should be `Awaited<PromiseType>`, ie:

```ts
{
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}
```

In `@remix-run/react` this works and the types look like this: 

```ts 
// @remix-run/react/dist/components.d.ts
export interface AwaitProps<Resolve> {
    children: React.ReactNode | ((value: Awaited<Resolve>) => React.ReactNode);
    errorElement?: React.ReactNode;
    resolve: Resolve;
}
```

### Actual Behavior

The type on the resolved item are fixed as `any`

**Comment by OnurGvnc** [comment] 2024-10-07 13:19
I've taken a quick look. When I made the [changes](https://github.com/OnurGvnc/react-router/commit/2ab91a33baa2c65e48c90cfe803af9a95155f831), I observed that it worked as expected.
However, I didn't open a PR because I'm not entirely sure about potential side effects.
The changes can be tested in this [TypeScript playground](https://www.typescriptlang.org/play/?ssl=7&ssc=1&pln=8&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wChSkAPSWOGATzCTgEEB3FYGZAZwgBsAbkmQA7ACZIoAMQCuojMAiiAPABUAfHAC8cABSk4ccShgoAXKw5ck49RoA0pAJQ6tydDAB0HjADkISXIqGnhgURgpTHRmNSh0AGtbAAUcEGAeZipIiR44VNwMpBUUUXotAG9DOAB9GHi0JPEAfksAIwgBVFFqmpMzVrhS+l6pHChB4dIAX2DqaDCIqJirThgCsB57OCqjNAALYH5xIlFLX28LgMk4AB9Vrl4BYTFJGXlFZXtqsegAUX4SBASAigwuPmIMGuSGqRD4QiQlgK6Uy23uahmc1CxiQaH4KCIcEwHxgSlEDxg9j0uzgByOJxBTiMvygAKBIJgTLgcOeSCc00s7DWGy2mmc50hXgAUgBlAAaXjZwIi5GJClJyjgAGFcJBRBy9K4aWhlDx4P0UDo4Pq2Pk0kUVDSjLJMlAAJLiSyiWQgNpSapGYCe60+v1QAN0LiAyxmqDhADmEZN4EBkWDHS6pWq0w0ej0PIRrm0lQjmRgalASAgshgeaLJaMje5SHhwmpEabLqkHssAEYuU3A8H+x3G6SYNG4ABySJmqcDwfJsCp2yWaL8TILozTZwR6YOOC9gAMJ93293sKQMFkUHJBibKiFXFHBeE2gqFumcAA9AAqOAqAAtIBdCMLYtLQEQGD8PQQx5MiDpOoOyEoahaHoWhXbusG3q+lIADco4YcRJGkXAQZeqGBFEWRtF0UY46TrGCaEfRbHsUuK7pp0gKlKx7ECSROa-t+o50scpzvvmLb1jsNHft+KEAHrNHANFENet4AeIwCCBoFRwl4jFINMKjfjpemjtMsxNt+GjVLusxAA)

**Comment by brophdawg11** [comment] 2024-10-10 20:03
This is a known issue at the moment - see https://reactrouter.com/dev/guides/upgrading/remix#typesafety for more information.  I'm going to close this out since it's not a bug but expected for right now

**Closed by brophdawg11** 2024-10-10 20:03 UTC
Labels: bug

**Comment by shmuli9** [comment] 2024-10-13 07:42
The link you posted is talking about why soon-to-be deprecated Remix API's aren't supported. Am I to understand that Await is one of those API's... does this mean RSC's are around the corner!!! 🚀🌔 🔷🙌

**Comment by brophdawg11** [comment] 2024-10-15 15:14
That's unrelated to RSC (which is coming in a 7.x version, just not in 7.0).  Await's primary purpose is to "unwrap" a promise during render which can be done via [`React.use`](https://react.dev/reference/react/use) in React 19, so the primary use case of `Await` is moot.  It may stick around as a convenience API that wraps `use` and because `errorElement` is a nice shorthand API.

**Comment by shmuli9** [comment] 2024-10-15 15:17
> That's unrelated to RSC (which is coming in a 7.x version, just not in 7.0).  Await's primary purpose is to "unwrap" a promise during render which can be done via [`React.use`](https://react.dev/reference/react/use) in React 19, so the primary use case of `Await` is moot.  It may stick around as a convenience API that wraps `use` and because `errorElement` is a nice shorthand API.

Ah, thanks for the background. So will 7.0 ship with React 19 or is that also coming in a future 7.x release?

**Comment by brophdawg11** [comment] 2024-10-15 15:21
RR will support 19 when it's released as stable - 18 will be the minimum supported version
